import type { CatalogCondition, CatalogTab } from "./catalog-types"

// Clean-room metadata inventory from the local 3X-UI v3.7.0 source.
// It intentionally contains no 3X-UI component, stylesheet, or implementation code.
// Source boundary: frontend/src/schemas/protocols/{inbound,stream,security}/*,
// frontend/src/pages/inbounds/form/{InboundFormModal,protocols,transport,security}/*.

const protocolIs = (value: string): CatalogCondition => ({ field: "protocol", equals: value })
const protocolIn = (value: string[]): CatalogCondition => ({ field: "protocol", equals: value })
const protocolNot = (value: string | string[]): CatalogCondition => ({ field: "protocol", notEquals: value })
const networkIs = (value: string): CatalogCondition => ({ field: "streamSettings.network", equals: value })
const networkIn = (value: string[]): CatalogCondition => ({ field: "streamSettings.network", equals: value })
const securityIs = (value: string): CatalogCondition => ({ field: "streamSettings.security", equals: value })
const securityIn = (value: string[]): CatalogCondition => ({ field: "streamSettings.security", equals: value })
const all = (...conditions: CatalogCondition[]): CatalogCondition[] => conditions

const PROTOCOL_OPTIONS = [
  { value: "vmess", label: "VMess" },
  { value: "vless", label: "VLESS" },
  { value: "trojan", label: "Trojan" },
  { value: "shadowsocks", label: "Shadowsocks" },
  { value: "wireguard", label: "WireGuard" },
  { value: "hysteria", label: "Hysteria" },
  { value: "http", label: "HTTP" },
  { value: "mixed", label: "Mixed (SOCKS/HTTP)" },
  { value: "tunnel", label: "Tunnel (dokodemo-door)" },
  { value: "tun", label: "TUN" },
  { value: "mtproto", label: "MTProto" },
  { value: "amneziawg", label: "AmneziaWG" },
]

const FLOW_OPTIONS = [
  { value: "", label: "无" },
  { value: "xtls-rprx-vision", label: "XTLS Vision" },
  { value: "xtls-rprx-vision-udp443", label: "XTLS Vision / UDP 443" },
]

const SECURITY_OPTIONS = [
  { value: "none", label: "无" },
  { value: "tls", label: "TLS" },
  { value: "reality", label: "REALITY" },
]

const TLS_ONLY_OPTIONS = [{ value: "tls", label: "TLS" }]

const NETWORK_OPTIONS = [
  { value: "tcp", label: "RAW / TCP" },
  { value: "kcp", label: "mKCP" },
  { value: "ws", label: "WebSocket" },
  { value: "grpc", label: "gRPC" },
  { value: "httpupgrade", label: "HTTPUpgrade" },
  { value: "xhttp", label: "XHTTP" },
]

const SS_METHOD_OPTIONS = [
  { value: "aes-256-gcm", label: "aes-256-gcm" },
  { value: "chacha20-poly1305", label: "chacha20-poly1305" },
  { value: "chacha20-ietf-poly1305", label: "chacha20-ietf-poly1305" },
  { value: "xchacha20-ietf-poly1305", label: "xchacha20-ietf-poly1305" },
  { value: "2022-blake3-aes-128-gcm", label: "2022-blake3-aes-128-gcm" },
  { value: "2022-blake3-aes-256-gcm", label: "2022-blake3-aes-256-gcm" },
  { value: "2022-blake3-chacha20-poly1305", label: "2022-blake3-chacha20-poly1305" },
]

const SS_2022_METHODS = SS_METHOD_OPTIONS.filter((option) => option.value.startsWith("2022-")).map(
  (option) => option.value,
)

const TCP_CONGESTION_OPTIONS = [
  { value: "bbr", label: "BBR" },
  { value: "cubic", label: "CUBIC" },
  { value: "reno", label: "Reno" },
]

const DOMAIN_STRATEGY_OPTIONS = [
  "AsIs",
  "UseIP",
  "UseIPv6v4",
  "UseIPv6",
  "UseIPv4v6",
  "UseIPv4",
  "ForceIP",
  "ForceIPv6v4",
  "ForceIPv6",
  "ForceIPv4v6",
  "ForceIPv4",
].map((value) => ({ value, label: value }))

const ADDRESS_PORT_STRATEGY_OPTIONS = [
  "none",
  "SrvPortOnly",
  "SrvAddressOnly",
  "SrvPortAndAddress",
  "TxtPortOnly",
  "TxtAddressOnly",
  "TxtPortAndAddress",
].map((value) => ({ value, label: value }))

const UTLS_OPTIONS = [
  "chrome",
  "firefox",
  "safari",
  "ios",
  "android",
  "edge",
  "360",
  "qq",
  "random",
  "randomized",
  "randomizednoalpn",
  "unsafe",
].map((value) => ({ value, label: value }))

const TLS_VERSION_OPTIONS = ["1.0", "1.1", "1.2", "1.3"].map((value) => ({ value, label: value }))
const ALPN_OPTIONS = ["h3", "h2", "http/1.1"].map((value) => ({ value, label: value }))
const TLS_USAGE_OPTIONS = ["encipherment", "verify", "issue"].map((value) => ({ value, label: value }))
const CURVE_OPTIONS = ["X25519MLKEM768", "X25519", "P-256", "P-384", "P-521"].map((value) => ({ value, label: value }))

const WIREGUARD_DOMAIN_OPTIONS = [
  "ForceIP",
  "ForceIPv4",
  "ForceIPv4v6",
  "ForceIPv6",
  "ForceIPv6v4",
].map((value) => ({ value, label: value }))

const SNIFFING_DEST_OPTIONS = ["http", "tls", "quic", "fakedns"].map((value) => ({ value, label: value }))

const TCP_FINAL_MASK_OPTIONS = ["fragment", "header-custom", "sudoku", "xmc"].map((value) => ({
  value,
  label: value,
}))
const HYSTERIA_FINAL_MASK_OPTIONS = [{ value: "salamander", label: "salamander" }]
const WIREGUARD_FINAL_MASK_OPTIONS = [{ value: "salamander", label: "salamander" }]
const KCP_FINAL_MASK_OPTIONS = ["mkcp-legacy", "xdns", "xicmp", "realm", "header-custom", "noise"].map(
  (value) => ({ value, label: value }),
)
const QUIC_CONGESTION_OPTIONS = ["reno", "bbr", "brutal", "force-brutal"].map((value) => ({ value, label: value }))
const QUIC_BBR_PROFILE_OPTIONS = ["conservative", "standard", "aggressive"].map((value) => ({ value, label: value }))

const XHTTP_MODE_OPTIONS = ["auto", "packet-up", "stream-up", "stream-one"].map((value) => ({ value, label: value }))
const XHTTP_PLACEMENT_OPTIONS = ["", "path", "header", "cookie", "query"].map((value) => ({
  value,
  label: value || "自动",
}))
const XHTTP_PADDING_PLACEMENT_OPTIONS = ["", "queryInHeader", "header", "cookie", "query"].map((value) => ({
  value,
  label: value || "自动",
}))
const XHTTP_PADDING_METHOD_OPTIONS = ["", "repeat-x", "tokenish"].map((value) => ({
  value,
  label: value || "自动",
}))
const XHTTP_UPLINK_PLACEMENT_OPTIONS = ["", "auto", "body", "header", "cookie"].map((value) => ({
  value,
  label: value || "自动",
}))
const XHTTP_METHOD_OPTIONS = ["", "POST", "PUT", "GET"].map((value) => ({
  value,
  label: value || "自动",
}))

const HYSTERIA_MASQUERADE_OPTIONS = ["", "proxy", "file", "string"].map((value) => ({
  value,
  label: value || "关闭",
}))

const TLS_CIPHER_OPTIONS = [
  "",
  "TLS_AES_128_GCM_SHA256",
  "TLS_AES_256_GCM_SHA384",
  "TLS_CHACHA20_POLY1305_SHA256",
  "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
  "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
  "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
  "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
  "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
  "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
  "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
  "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
  "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
  "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
].map((value) => ({ value, label: value || "自动" }))

const PROTOCOL_CLIENTS_HELP =
  "这里只描述协议认证集合；邮箱、限额、重置、到期、订阅绑定等 XBoard 客户端业务字段不属于此目录。"

const streamProtocol = protocolIn(["vmess", "vless", "trojan", "shadowsocks", "hysteria", "wireguard", "tunnel"])
const selectableTransportProtocol = protocolIn(["vmess", "vless", "trojan", "shadowsocks"])
const tlsProtocol = protocolIn(["vmess", "vless", "trojan", "shadowsocks"])
const realityProtocol = protocolIn(["vless", "trojan"])

export const inboundCatalog: CatalogTab[] = [
  {
    id: "basic",
    title: "基础运行",
    description: "描述监听器本身的运行字段；不包含分享、订阅排序、配额或生命周期业务策略。",
    sections: [
      {
        id: "runtime",
        title: "运行入口",
        fields: [
          {
            key: "enable",
            label: "启用监听",
            control: "switch",
            defaultValue: true,
            description: "决定该入站是否参与运行时配置。",
          },
          {
            key: "remark",
            label: "备注",
            control: "text",
            placeholder: "例如：主站接入",
            description: "仅作为运维识别名称。",
          },
          {
            key: "protocol",
            label: "协议",
            control: "select",
            options: PROTOCOL_OPTIONS,
            defaultValue: "vless",
            description: "选择后决定 settings、传输与安全字段的可用范围。",
          },
          {
            key: "listen",
            label: "监听地址",
            control: "text",
            placeholder: "留空监听所有地址，例如 127.0.0.1",
            description: "可填写 IP、主机名或 Unix socket 路径；留空由内核监听全部地址。",
          },
          {
            key: "port",
            label: "监听端口",
            control: "number",
            placeholder: "443",
            description: "通常为 1–65535；Unix socket 监听时可使用 0。",
          },
          {
            key: "tag",
            label: "运行标签",
            control: "text",
            placeholder: "留空自动生成，例如 vless-443",
            description: "运行时路由和链式出站引用的唯一标签；空值时由控制面生成。",
          },
        ],
      },
    ],
  },
  {
    id: "protocol",
    title: "协议",
    description: "协议 settings 的可配置字段；客户端业务属性由独立客户端管理。",
    sections: [
      {
        id: "vless",
        title: "VLESS",
        fields: [
          {
            key: "settings.decryption",
            label: "服务端解密",
            control: "text",
            placeholder: "none 或生成的 vlessenc 值",
            sensitive: true,
            showWhen: protocolIs("vless"),
            description: "服务端解密值；普通 VLESS 使用 none，启用 VLESS 加密时由内核生成。",
          },
          {
            key: "settings.encryption",
            label: "客户端加密",
            control: "text",
            placeholder: "none 或生成的 vlessenc 值",
            sensitive: true,
            showWhen: protocolIs("vless"),
            description: "用于链接/订阅传播的客户端加密值；不要把它理解为 TLS。",
          },
          {
            key: "settings.testseed",
            label: "Vision 测试种子",
            control: "code",
            placeholder: "[900, 500, 900, 256]",
            rows: 2,
            showWhen: all(protocolIs("vless"), networkIs("tcp"), securityIn(["tls", "reality"])),
            description: "仅在 TCP + TLS/REALITY 时可用，服务于 xtls-rprx-vision 客户端；其他流控会忽略。",
          },
          {
            key: "settings.fallbacks",
            label: "回落规则集合",
            control: "code",
            placeholder: '[{"name":"example.com","alpn":"h2","path":"/","dest":"127.0.0.1:8080","xver":0}]',
            rows: 5,
            showWhen: all(protocolIs("vless"), networkIs("tcp"), securityIn(["tls", "reality"])),
            description: "运行时字段为 name、alpn、path、dest、xver；子入站关联与排序由 XBoard 业务层单独维护。",
          },
          {
            key: "settings.clients",
            label: "客户端认证集合",
            control: "code",
            placeholder: '[{"id":"uuid","flow":""}]',
            rows: 4,
            sensitive: true,
            showWhen: protocolIs("vless"),
            description: `${PROTOCOL_CLIENTS_HELP} VLESS 运行时字段至少包含 id，可选 flow。`,
          },
          {
            key: "settings.clients[].flow",
            label: "客户端流控枚举",
            control: "select",
            options: FLOW_OPTIONS,
            showWhen: protocolIs("vless"),
            description: "这是 VLESS 客户端对象中的运行时字段；客户端数组行由独立编辑器承载。",
          },
        ],
      },
      {
        id: "vmess",
        title: "VMess",
        fields: [
          {
            key: "settings.clients",
            label: "客户端认证集合",
            control: "code",
            placeholder: '[{"id":"uuid","security":"auto","alterId":0}]',
            rows: 4,
            sensitive: true,
            showWhen: protocolIs("vmess"),
            description: `${PROTOCOL_CLIENTS_HELP} VMess 运行时字段为 id、security、alterId。`,
          },
        ],
      },
      {
        id: "trojan",
        title: "Trojan",
        fields: [
          {
            key: "settings.clients",
            label: "客户端认证集合",
            control: "code",
            placeholder: '[{"password":"secret"}]',
            rows: 4,
            sensitive: true,
            showWhen: protocolIs("trojan"),
            description: `${PROTOCOL_CLIENTS_HELP} Trojan 运行时字段为 password。`,
          },
          {
            key: "settings.fallbacks",
            label: "回落规则集合",
            control: "code",
            placeholder: '[{"name":"example.com","alpn":"h2","path":"/","dest":"127.0.0.1:8080","xver":0}]',
            rows: 5,
            showWhen: all(protocolIs("trojan"), networkIs("tcp"), securityIn(["tls", "reality"])),
            description: "运行时字段为 name、alpn、path、dest、xver；子入站关联与排序由 XBoard 业务层单独维护。",
          },
        ],
      },
      {
        id: "shadowsocks",
        title: "Shadowsocks",
        fields: [
          {
            key: "settings.method",
            label: "加密方法",
            control: "select",
            options: SS_METHOD_OPTIONS,
            showWhen: protocolIs("shadowsocks"),
            description: "选择后决定密码格式以及是否启用 Shadowsocks 2022 单入站密码。",
          },
          {
            key: "settings.password",
            label: "入站密码",
            control: "password",
            placeholder: "Shadowsocks 2022 的预共享密钥",
            sensitive: true,
            showWhen: all(protocolIs("shadowsocks"), { field: "settings.method", equals: SS_2022_METHODS }),
            description: "仅 Shadowsocks 2022 方法在此使用入站级密码；普通多用户密码在客户端集合中。",
          },
          {
            key: "settings.network",
            label: "允许网络",
            control: "select",
            options: [
              { value: "tcp,udp", label: "TCP + UDP" },
              { value: "tcp", label: "TCP" },
              { value: "udp", label: "UDP" },
            ],
            showWhen: protocolIs("shadowsocks"),
          },
          {
            key: "settings.ivCheck",
            label: "IV 检查",
            control: "switch",
            defaultValue: false,
            showWhen: protocolIs("shadowsocks"),
            description: "保留 3X-UI 的兼容字段；是否实际生效由内核版本决定。",
          },
          {
            key: "settings.clients",
            label: "客户端认证集合",
            control: "code",
            placeholder: '[{"method":"","password":"secret"}]',
            rows: 4,
            sensitive: true,
            showWhen: protocolIs("shadowsocks"),
            description: `${PROTOCOL_CLIENTS_HELP} 2022 多用户行可包含 method 与 password。`,
          },
        ],
      },
      {
        id: "wireguard",
        title: "WireGuard",
        fields: [
          {
            key: "settings.secretKey",
            label: "服务端私钥",
            control: "password",
            placeholder: "Base64 私钥",
            sensitive: true,
            showWhen: protocolIs("wireguard"),
            description: "服务端身份私钥；公钥由私钥派生。",
          },
          {
            key: "settings.publicKey",
            label: "服务端公钥",
            control: "text",
            placeholder: "由私钥派生",
            showWhen: protocolIs("wireguard"),
            description: "只读派生值，运行时不需要手工编辑。",
          },
          {
            key: "settings.subnetIp",
            label: "地址池网络地址",
            control: "text",
            placeholder: "10.0.0.0",
            showWhen: protocolIs("wireguard"),
          },
          {
            key: "settings.subnetCidr",
            label: "地址池前缀长度",
            control: "number",
            placeholder: "24",
            showWhen: protocolIs("wireguard"),
          },
          {
            key: "settings.mtu",
            label: "MTU",
            control: "number",
            placeholder: "1420",
            showWhen: protocolIs("wireguard"),
          },
          {
            key: "settings.dns",
            label: "隧道 DNS",
            control: "text",
            placeholder: "1.1.1.1, 1.0.0.1",
            showWhen: protocolIs("wireguard"),
          },
          {
            key: "settings.noKernelTun",
            label: "不使用内核 TUN",
            control: "switch",
            defaultValue: false,
            showWhen: protocolIs("wireguard"),
          },
          {
            key: "settings.domainStrategy",
            label: "域名解析策略",
            control: "select",
            options: WIREGUARD_DOMAIN_OPTIONS,
            showWhen: protocolIs("wireguard"),
          },
          {
            key: "settings.peers",
            label: "Peer 集合",
            control: "code",
            placeholder: '[{"publicKey":"...","allowedIPs":["10.0.0.2/32"],"keepAlive":0}]',
            rows: 4,
            sensitive: true,
            showWhen: protocolIs("wireguard"),
            description: "运行时 Peer 字段为 publicKey、preSharedKey、allowedIPs、keepAlive；客户端业务字段不在此处。",
          },
        ],
      },
      {
        id: "hysteria",
        title: "Hysteria",
        fields: [
          {
            key: "settings.version",
            label: "协议版本",
            control: "number",
            defaultValue: 2,
            showWhen: protocolIs("hysteria"),
            description: "本地 3X-UI 将入站版本固定为 2。",
          },
          {
            key: "settings.clients",
            label: "客户端认证集合",
            control: "code",
            placeholder: '[{"auth":"token"}]',
            rows: 4,
            sensitive: true,
            showWhen: protocolIs("hysteria"),
            description: `${PROTOCOL_CLIENTS_HELP} Hysteria 运行时字段为 auth。`,
          },
        ],
      },
      {
        id: "http",
        title: "HTTP 代理",
        fields: [
          {
            key: "settings.accounts",
            label: "账号集合",
            control: "code",
            placeholder: '[{"user":"operator","pass":"secret"}]',
            rows: 4,
            sensitive: true,
            showWhen: protocolIs("http"),
            description: "每行包含 user 与 pass；这是 HTTP 代理自身的运行时认证，不是 XBoard 用户资料。",
          },
          {
            key: "settings.allowTransparent",
            label: "允许透明转发",
            control: "switch",
            defaultValue: false,
            showWhen: protocolIs("http"),
            description: "允许把原始 Host 参与转发；只对 HTTP 代理入站生效。",
          },
        ],
      },
      {
        id: "mixed",
        title: "Mixed 代理",
        fields: [
          {
            key: "settings.auth",
            label: "认证模式",
            control: "select",
            options: [
              { value: "password", label: "密码" },
              { value: "noauth", label: "无认证" },
            ],
            defaultValue: "password",
            showWhen: protocolIs("mixed"),
          },
          {
            key: "settings.accounts",
            label: "账号集合",
            control: "code",
            placeholder: '[{"user":"operator","pass":"secret"}]',
            rows: 4,
            sensitive: true,
            showWhen: all(protocolIs("mixed"), { field: "settings.auth", equals: "password" }),
            description: "只有 password 模式发送 accounts；noauth 时该集合从 wire payload 省略。",
          },
          {
            key: "settings.udp",
            label: "启用 UDP",
            control: "switch",
            defaultValue: false,
            showWhen: protocolIs("mixed"),
          },
          {
            key: "settings.ip",
            label: "UDP 地址",
            control: "text",
            placeholder: "127.0.0.1",
            showWhen: all(protocolIs("mixed"), { field: "settings.udp", equals: true }),
            description: "仅在 Mixed UDP 开启时使用。",
          },
        ],
      },
      {
        id: "tunnel",
        title: "Tunnel / dokodemo-door",
        fields: [
          {
            key: "settings.rewriteAddress",
            label: "重写目标地址",
            control: "text",
            placeholder: "目标主机或 IP",
            showWhen: protocolIs("tunnel"),
          },
          {
            key: "settings.rewritePort",
            label: "重写目标端口",
            control: "number",
            placeholder: "可选",
            showWhen: protocolIs("tunnel"),
          },
          {
            key: "settings.allowedNetwork",
            label: "允许网络",
            control: "select",
            options: [
              { value: "tcp,udp", label: "TCP + UDP" },
              { value: "tcp", label: "TCP" },
              { value: "udp", label: "UDP" },
            ],
            showWhen: protocolIs("tunnel"),
          },
          {
            key: "settings.portMap",
            label: "端口映射",
            control: "code",
            placeholder: '{"443":"127.0.0.1:8443"}',
            rows: 3,
            showWhen: protocolIs("tunnel"),
            description: "键和值均为字符串；用于把监听端口映射到目标端口。",
          },
          {
            key: "settings.followRedirect",
            label: "跟随重定向",
            control: "switch",
            defaultValue: false,
            showWhen: protocolIs("tunnel"),
          },
        ],
      },
      {
        id: "tun",
        title: "TUN",
        fields: [
          {
            key: "settings.name",
            label: "接口名称",
            control: "text",
            placeholder: "xray0",
            showWhen: protocolIs("tun"),
          },
          {
            key: "settings.mtu",
            label: "MTU",
            control: "number",
            placeholder: "1500",
            showWhen: protocolIs("tun"),
          },
          {
            key: "settings.gateway",
            label: "网关地址集合",
            control: "tags",
            placeholder: "10.0.0.1/16，或 fc00::1/64",
            showWhen: protocolIs("tun"),
          },
          {
            key: "settings.dns",
            label: "DNS 集合",
            control: "tags",
            placeholder: "1.1.1.1，8.8.8.8",
            showWhen: protocolIs("tun"),
          },
          {
            key: "settings.userLevel",
            label: "用户级别",
            control: "number",
            defaultValue: 0,
            showWhen: protocolIs("tun"),
          },
          {
            key: "settings.autoSystemRoutingTable",
            label: "自动系统路由",
            control: "tags",
            placeholder: "0.0.0.0/0，或 ::/0",
            showWhen: protocolIs("tun"),
            description: "为空时不自动写入系统路由表。",
          },
          {
            key: "settings.autoOutboundsInterface",
            label: "自动出站接口",
            control: "text",
            placeholder: "auto 或 eth0",
            showWhen: protocolIs("tun"),
          },
        ],
      },
      {
        id: "mtproto",
        title: "MTProto",
        fields: [
          {
            key: "settings.fakeTlsDomain",
            label: "FakeTLS 域名",
            control: "text",
            placeholder: "www.cloudflare.com",
            showWhen: protocolIs("mtproto"),
            description: "mtg-multi 对外使用的默认 FakeTLS 域名。",
          },
          {
            key: "settings.domainFronting.ip",
            label: "域前置地址",
            control: "text",
            placeholder: "127.0.0.1",
            showWhen: protocolIs("mtproto"),
          },
          {
            key: "settings.domainFronting.port",
            label: "域前置端口",
            control: "number",
            placeholder: "443",
            showWhen: protocolIs("mtproto"),
          },
          {
            key: "settings.domainFronting.proxyProtocol",
            label: "域前置 PROXY 协议",
            control: "switch",
            showWhen: protocolIs("mtproto"),
          },
          {
            key: "settings.proxyProtocolListener",
            label: "监听 PROXY 协议",
            control: "switch",
            showWhen: protocolIs("mtproto"),
          },
          {
            key: "settings.preferIp",
            label: "出站 IP 偏好",
            control: "select",
            options: [
              { value: "prefer-ipv6", label: "优先 IPv6" },
              { value: "prefer-ipv4", label: "优先 IPv4" },
              { value: "only-ipv6", label: "仅 IPv6" },
              { value: "only-ipv4", label: "仅 IPv4" },
            ],
            showWhen: protocolIs("mtproto"),
          },
          {
            key: "settings.debug",
            label: "调试日志",
            control: "switch",
            showWhen: protocolIs("mtproto"),
          },
          {
            key: "settings.throttleMaxConnections",
            label: "最大并发连接",
            control: "number",
            placeholder: "0 表示不限",
            showWhen: protocolIs("mtproto"),
          },
          {
            key: "settings.routeThroughXray",
            label: "经 Xray 路由",
            control: "switch",
            showWhen: protocolIs("mtproto"),
          },
          {
            key: "settings.outboundTag",
            label: "路由出站标签",
            control: "text",
            placeholder: "可选的 outbound tag",
            showWhen: all(protocolIs("mtproto"), { field: "settings.routeThroughXray", equals: true }),
            description: "只有经 Xray 路由开启时才指定；空值使用默认出站。",
          },
          {
            key: "settings.publicIpv4",
            label: "公网 IPv4",
            control: "text",
            placeholder: "203.0.113.10",
            showWhen: protocolIs("mtproto"),
          },
          {
            key: "settings.publicIpv6",
            label: "公网 IPv6",
            control: "text",
            placeholder: "2001:db8::10",
            showWhen: protocolIs("mtproto"),
          },
          {
            key: "settings.clients",
            label: "客户端认证集合",
            control: "code",
            placeholder: '[{"secret":"ee...","adTag":""}]',
            rows: 4,
            sensitive: true,
            showWhen: protocolIs("mtproto"),
            description: `${PROTOCOL_CLIENTS_HELP} MTProto 运行时字段为 secret 与可选 adTag。`,
          },
        ],
      },
      {
        id: "amneziawg",
        title: "AmneziaWG",
        fields: [
          {
            key: "settings.server.privateKey",
            label: "服务端私钥",
            control: "password",
            placeholder: "Base64 私钥",
            sensitive: true,
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.publicKey",
            label: "服务端公钥",
            control: "text",
            placeholder: "由私钥派生",
            showWhen: protocolIs("amneziawg"),
            description: "由服务端私钥派生；用于展示和核对，不应手工覆盖。",
          },
          {
            key: "settings.server.subnetIp",
            label: "地址池网络地址",
            control: "text",
            placeholder: "10.8.1.0",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.subnetCidr",
            label: "地址池前缀长度",
            control: "number",
            placeholder: "24",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.mtu",
            label: "MTU",
            control: "number",
            placeholder: "1420",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.primaryDns",
            label: "主 DNS",
            control: "text",
            placeholder: "8.8.8.8",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.secondaryDns",
            label: "备用 DNS",
            control: "text",
            placeholder: "8.8.4.4",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.externalInterface",
            label: "外部网络接口",
            control: "text",
            placeholder: "eth0",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.ipv6Enabled",
            label: "启用 IPv6",
            control: "switch",
            defaultValue: false,
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.ipv6Subnet",
            label: "IPv6 地址池",
            control: "text",
            placeholder: "fd86:ea04:1115::/64",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.ipv6ExternalInterface",
            label: "IPv6 外部接口",
            control: "text",
            placeholder: "eth0",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.jc",
            label: "Jc",
            control: "number",
            placeholder: "5",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.jmin",
            label: "Jmin",
            control: "number",
            placeholder: "10",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.jmax",
            label: "Jmax",
            control: "number",
            placeholder: "50",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.s1",
            label: "S1",
            control: "number",
            placeholder: "30",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.s2",
            label: "S2",
            control: "number",
            placeholder: "45",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.s3",
            label: "S3",
            control: "number",
            placeholder: "10",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.s4",
            label: "S4",
            control: "number",
            placeholder: "5",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.h1",
            label: "H1",
            control: "text",
            placeholder: "1 或 100-800",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.h2",
            label: "H2",
            control: "text",
            placeholder: "2 或 100-800",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.h3",
            label: "H3",
            control: "text",
            placeholder: "3 或 100-800",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.h4",
            label: "H4",
            control: "text",
            placeholder: "4 或 100-800",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.i1",
            label: "I1",
            control: "text",
            placeholder: "<r 64>",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.i2",
            label: "I2",
            control: "text",
            placeholder: "<r 64>",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.i3",
            label: "I3",
            control: "text",
            placeholder: "<r 64>",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.i4",
            label: "I4",
            control: "text",
            placeholder: "<r 64>",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.i5",
            label: "I5",
            control: "text",
            placeholder: "<r 64>",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.headerProtectionKey",
            label: "Header Protection Key",
            control: "password",
            sensitive: true,
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.contentPaddingAddition",
            label: "Content Padding Addition",
            control: "text",
            placeholder: "8-64",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.rekeyAfterTime",
            label: "Rekey After Time",
            control: "text",
            placeholder: "100-160",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.rekeyTimeout",
            label: "Rekey Timeout",
            control: "text",
            placeholder: "3-10",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.rejectAfterTime",
            label: "Reject After Time",
            control: "text",
            placeholder: "190-250",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.keepaliveTimeout",
            label: "Keepalive Timeout",
            control: "text",
            placeholder: "8-20",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.maxHandshakeAttempts",
            label: "最大握手尝试次数",
            control: "text",
            placeholder: "15-50",
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.randomTrailers",
            label: "随机 Trailers",
            control: "switch",
            defaultValue: false,
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.server.disableCookies",
            label: "禁用 Cookies",
            control: "switch",
            defaultValue: false,
            showWhen: protocolIs("amneziawg"),
          },
          {
            key: "settings.clients",
            label: "客户端 Peer 集合",
            control: "code",
            placeholder: '[{"publicKey":"...","allowedIPs":["10.8.1.2/32"],"forwardedPorts":""}]',
            rows: 4,
            sensitive: true,
            showWhen: protocolIs("amneziawg"),
            description: `${PROTOCOL_CLIENTS_HELP} AmneziaWG 运行时 Peer 字段为密钥、allowedIPs、keepAlive 与 forwardedPorts。`,
          },
        ],
      },
    ],
  },
  {
    id: "transport",
    title: "传输",
    description: "只描述 3X-UI 入站 streamSettings 的传输参数；协议无传输层时不显示无关字段。",
    sections: [
      {
        id: "network",
        title: "传输方式",
        fields: [
          {
            key: "streamSettings.network",
            label: "网络类型",
            control: "select",
            options: NETWORK_OPTIONS,
            showWhen: selectableTransportProtocol,
            description: "VMess、VLESS、Trojan、Shadowsocks 可选择 RAW/TCP、mKCP、WebSocket、gRPC、HTTPUpgrade 或 XHTTP。",
          },
          {
            key: "streamSettings.network",
            label: "专用网络类型",
            control: "text",
            showWhen: protocolIs("hysteria"),
            description: "Hysteria 使用专用 hysteria streamSettings；WireGuard 与 Tunnel 没有可选传输层。",
          },
        ],
      },
      {
        id: "tcp",
        title: "RAW / TCP",
        fields: [
          {
            key: "streamSettings.tcpSettings.acceptProxyProtocol",
            label: "接收 PROXY Protocol",
            control: "switch",
            defaultValue: false,
            showWhen: networkIs("tcp"),
            description: "把前置负载均衡器传入的 PROXY v1/v2 地址交给 Xray 解析。",
          },
          {
            key: "streamSettings.tcpSettings.header.type",
            label: "TCP 头类型",
            control: "select",
            options: [
              { value: "none", label: "无" },
              { value: "http", label: "HTTP 伪装" },
            ],
            showWhen: networkIs("tcp"),
            description: "HTTP 头会产生 request/response 两组伪装字段。",
          },
          {
            key: "streamSettings.tcpSettings.header.request",
            label: "HTTP 请求头",
            control: "code",
            placeholder: '{"version":"1.1","method":"GET","path":["/"],"headers":{}}',
            rows: 4,
            showWhen: all(networkIs("tcp"), {
              field: "streamSettings.tcpSettings.header.type",
              equals: "http",
            }),
            description: "运行时字段为 version、method、path 数组和 headers 映射。",
          },
          {
            key: "streamSettings.tcpSettings.header.response",
            label: "HTTP 响应头",
            control: "code",
            placeholder: '{"version":"1.1","status":"200","reason":"OK","headers":{}}',
            rows: 4,
            showWhen: all(networkIs("tcp"), {
              field: "streamSettings.tcpSettings.header.type",
              equals: "http",
            }),
            description: "运行时字段为 version、status、reason 和 headers 映射。",
          },
        ],
      },
      {
        id: "websocket",
        title: "WebSocket",
        fields: [
          {
            key: "streamSettings.wsSettings.acceptProxyProtocol",
            label: "接收 PROXY Protocol",
            control: "switch",
            defaultValue: false,
            showWhen: networkIs("ws"),
          },
          {
            key: "streamSettings.wsSettings.path",
            label: "路径",
            control: "text",
            placeholder: "/ws",
            showWhen: networkIs("ws"),
          },
          {
            key: "streamSettings.wsSettings.host",
            label: "Host",
            control: "text",
            placeholder: "example.com",
            showWhen: networkIs("ws"),
          },
          {
            key: "streamSettings.wsSettings.headers",
            label: "额外请求头",
            control: "code",
            placeholder: '{"Host":"example.com","X-Forwarded-Proto":"https"}',
            rows: 3,
            showWhen: networkIs("ws"),
            description: "使用字符串键值映射；Host 也可用单独字段表达。",
          },
          {
            key: "streamSettings.wsSettings.heartbeatPeriod",
            label: "心跳周期（秒）",
            control: "number",
            placeholder: "0",
            showWhen: networkIs("ws"),
            description: "0 表示不额外发送心跳。",
          },
        ],
      },
      {
        id: "grpc",
        title: "gRPC",
        fields: [
          {
            key: "streamSettings.grpcSettings.serviceName",
            label: "服务名",
            control: "text",
            placeholder: "grpc-service",
            showWhen: networkIs("grpc"),
          },
          {
            key: "streamSettings.grpcSettings.authority",
            label: "Authority",
            control: "text",
            placeholder: "example.com",
            showWhen: networkIs("grpc"),
          },
          {
            key: "streamSettings.grpcSettings.multiMode",
            label: "多路模式",
            control: "switch",
            defaultValue: false,
            showWhen: networkIs("grpc"),
            description: "允许多个并发 gRPC 流复用同一连接。",
          },
        ],
      },
      {
        id: "httpupgrade",
        title: "HTTPUpgrade",
        fields: [
          {
            key: "streamSettings.httpupgradeSettings.acceptProxyProtocol",
            label: "接收 PROXY Protocol",
            control: "switch",
            defaultValue: false,
            showWhen: networkIs("httpupgrade"),
          },
          {
            key: "streamSettings.httpupgradeSettings.path",
            label: "路径",
            control: "text",
            placeholder: "/upgrade",
            showWhen: networkIs("httpupgrade"),
          },
          {
            key: "streamSettings.httpupgradeSettings.host",
            label: "Host",
            control: "text",
            placeholder: "example.com",
            showWhen: networkIs("httpupgrade"),
          },
          {
            key: "streamSettings.httpupgradeSettings.headers",
            label: "额外请求头",
            control: "code",
            placeholder: '{"X-Forwarded-Proto":"https"}',
            rows: 3,
            showWhen: networkIs("httpupgrade"),
          },
        ],
      },
      {
        id: "mkcp",
        title: "mKCP",
        fields: [
          {
            key: "streamSettings.kcpSettings.mtu",
            label: "MTU",
            control: "number",
            defaultValue: 1350,
            placeholder: "576–1460",
            showWhen: networkIs("kcp"),
          },
          {
            key: "streamSettings.kcpSettings.tti",
            label: "TTI（毫秒）",
            control: "number",
            defaultValue: 50,
            placeholder: "10–100",
            showWhen: networkIs("kcp"),
          },
          {
            key: "streamSettings.kcpSettings.uplinkCapacity",
            label: "上行容量（MB/s）",
            control: "number",
            defaultValue: 5,
            placeholder: "0",
            showWhen: networkIs("kcp"),
          },
          {
            key: "streamSettings.kcpSettings.downlinkCapacity",
            label: "下行容量（MB/s）",
            control: "number",
            defaultValue: 20,
            placeholder: "0",
            showWhen: networkIs("kcp"),
          },
          {
            key: "streamSettings.kcpSettings.cwndMultiplier",
            label: "拥塞窗口倍率",
            control: "number",
            defaultValue: 3,
            placeholder: "1–20",
            showWhen: networkIs("kcp"),
          },
          {
            key: "streamSettings.kcpSettings.maxSendingWindow",
            label: "最大发送窗口",
            control: "number",
            placeholder: "0",
            showWhen: networkIs("kcp"),
          },
        ],
      },
      {
        id: "xhttp",
        title: "XHTTP",
        fields: [
          {
            key: "streamSettings.xhttpSettings.path",
            label: "路径",
            control: "text",
            defaultValue: "/",
            placeholder: "/xhttp",
            showWhen: networkIs("xhttp"),
          },
          {
            key: "streamSettings.xhttpSettings.host",
            label: "Host",
            control: "text",
            placeholder: "example.com",
            showWhen: networkIs("xhttp"),
          },
          {
            key: "streamSettings.xhttpSettings.mode",
            label: "模式",
            control: "select",
            options: XHTTP_MODE_OPTIONS,
            defaultValue: "auto",
            showWhen: networkIs("xhttp"),
            description: "auto、packet-up、stream-up、stream-one 对应 xray-core SplitHTTP 模式。",
          },
          {
            key: "streamSettings.xhttpSettings.xPaddingBytes",
            label: "Padding 字节范围",
            control: "text",
            defaultValue: "100-1000",
            placeholder: "100-1000",
            showWhen: networkIs("xhttp"),
          },
          {
            key: "streamSettings.xhttpSettings.xPaddingObfsMode",
            label: "启用 Padding 混淆",
            control: "switch",
            defaultValue: false,
            showWhen: networkIs("xhttp"),
          },
          {
            key: "streamSettings.xhttpSettings.xPaddingKey",
            label: "Padding Key",
            control: "text",
            showWhen: all(networkIs("xhttp"), { field: "streamSettings.xhttpSettings.xPaddingObfsMode", equals: true }),
          },
          {
            key: "streamSettings.xhttpSettings.xPaddingHeader",
            label: "Padding Header",
            control: "text",
            showWhen: all(networkIs("xhttp"), { field: "streamSettings.xhttpSettings.xPaddingObfsMode", equals: true }),
          },
          {
            key: "streamSettings.xhttpSettings.xPaddingPlacement",
            label: "Padding 位置",
            control: "select",
            options: XHTTP_PADDING_PLACEMENT_OPTIONS,
            showWhen: all(networkIs("xhttp"), { field: "streamSettings.xhttpSettings.xPaddingObfsMode", equals: true }),
          },
          {
            key: "streamSettings.xhttpSettings.xPaddingMethod",
            label: "Padding 方法",
            control: "select",
            options: XHTTP_PADDING_METHOD_OPTIONS,
            showWhen: all(networkIs("xhttp"), { field: "streamSettings.xhttpSettings.xPaddingObfsMode", equals: true }),
          },
          {
            key: "streamSettings.xhttpSettings.sessionIDPlacement",
            label: "Session ID 位置",
            control: "select",
            options: XHTTP_PLACEMENT_OPTIONS,
            showWhen: networkIs("xhttp"),
          },
          {
            key: "streamSettings.xhttpSettings.sessionIDKey",
            label: "Session ID 键",
            control: "text",
            placeholder: "sid",
            showWhen: all(networkIs("xhttp"), {
              field: "streamSettings.xhttpSettings.sessionIDPlacement",
              equals: ["header", "cookie", "query"],
            }),
          },
          {
            key: "streamSettings.xhttpSettings.sessionIDTable",
            label: "Session ID 字符表",
            control: "text",
            placeholder: "Base62 或自定义 ASCII 字符表",
            showWhen: networkIs("xhttp"),
            description: "可填 ALPHABET、Alphabet、BASE36、Base62、HEX、alphabet、base36、hex、number 或自定义 ASCII 字符集。",
          },
          {
            key: "streamSettings.xhttpSettings.sessionIDLength",
            label: "Session ID 长度",
            control: "text",
            placeholder: "8-16",
            showWhen: all(networkIs("xhttp"), {
              field: "streamSettings.xhttpSettings.sessionIDTable",
              notEquals: "",
            }),
          },
          {
            key: "streamSettings.xhttpSettings.seqPlacement",
            label: "序号位置",
            control: "select",
            options: XHTTP_PLACEMENT_OPTIONS,
            showWhen: networkIs("xhttp"),
          },
          {
            key: "streamSettings.xhttpSettings.seqKey",
            label: "序号键",
            control: "text",
            placeholder: "seq",
            showWhen: all(networkIs("xhttp"), {
              field: "streamSettings.xhttpSettings.seqPlacement",
              equals: ["header", "cookie", "query"],
            }),
          },
          {
            key: "streamSettings.xhttpSettings.uplinkDataPlacement",
            label: "上行数据位置",
            control: "select",
            options: XHTTP_UPLINK_PLACEMENT_OPTIONS,
            showWhen: all(networkIs("xhttp"), {
              field: "streamSettings.xhttpSettings.mode",
              equals: "packet-up",
            }),
          },
          {
            key: "streamSettings.xhttpSettings.uplinkDataKey",
            label: "上行数据键",
            control: "text",
            placeholder: "data",
            showWhen: all(
              networkIs("xhttp"),
              { field: "streamSettings.xhttpSettings.mode", equals: "packet-up" },
              { field: "streamSettings.xhttpSettings.uplinkDataPlacement", equals: ["auto", "header", "cookie"] },
            ),
          },
          {
            key: "streamSettings.xhttpSettings.scMaxEachPostBytes",
            label: "单个 POST 最大字节数",
            control: "text",
            placeholder: "留空使用内核默认值",
            showWhen: all(networkIs("xhttp"), {
              field: "streamSettings.xhttpSettings.mode",
              equals: ["auto", "packet-up"],
            }),
          },
          {
            key: "streamSettings.xhttpSettings.noSSEHeader",
            label: "省略 SSE 头",
            control: "switch",
            defaultValue: false,
            showWhen: networkIs("xhttp"),
          },
          {
            key: "streamSettings.xhttpSettings.scMaxBufferedPosts",
            label: "最大缓存 POST 数",
            control: "number",
            defaultValue: 30,
            showWhen: all(networkIs("xhttp"), {
              field: "streamSettings.xhttpSettings.mode",
              equals: ["auto", "packet-up", "stream-up"],
            }),
          },
          {
            key: "streamSettings.xhttpSettings.scStreamUpServerSecs",
            label: "Stream-up 服务端秒数",
            control: "text",
            defaultValue: "20-80",
            placeholder: "20-80",
            showWhen: all(networkIs("xhttp"), { field: "streamSettings.xhttpSettings.mode", equals: "stream-up" }),
          },
          {
            key: "streamSettings.xhttpSettings.serverMaxHeaderBytes",
            label: "服务端最大头字节数",
            control: "number",
            defaultValue: 0,
            showWhen: networkIs("xhttp"),
          },
          {
            key: "streamSettings.xhttpSettings.uplinkHTTPMethod",
            label: "上行 HTTP 方法",
            control: "select",
            options: XHTTP_METHOD_OPTIONS,
            showWhen: networkIs("xhttp"),
            description: "GET 仅适用于 packet-up；空值表示由订阅/内核默认处理。",
          },
          {
            key: "streamSettings.xhttpSettings.headers",
            label: "XHTTP 头映射",
            control: "code",
            placeholder: '{"X-Forwarded-Proto":"https"}',
            rows: 3,
            showWhen: networkIs("xhttp"),
          },
          {
            key: "streamSettings.xhttpSettings.scMinPostsIntervalMs",
            label: "POST 最小间隔（毫秒）",
            control: "text",
            placeholder: "留空使用默认值",
            showWhen: all(networkIs("xhttp"), { field: "streamSettings.xhttpSettings.mode", equals: ["auto", "packet-up"] }),
            description: "入站只保留用于分享链接传播的非默认值；不是 XBoard 流量统计字段。",
          },
          {
            key: "streamSettings.xhttpSettings.xmux",
            label: "XMUX 参数",
            control: "code",
            placeholder: '{"maxConcurrency":"16-32","maxConnections":0,"cMaxReuseTimes":0,"hMaxRequestTimes":"600-900","hMaxReusableSecs":"1800-3000","hKeepAlivePeriod":0}',
            rows: 5,
            showWhen: networkIs("xhttp"),
            description: "可选连接复用对象；maxConcurrency 与 maxConnections 是互斥策略。enableXmux 仅是编辑器展开状态，不写入线协议。",
          },
          {
            key: "streamSettings.xhttpSettings.enableXmux",
            label: "启用 XMUX 编辑器",
            control: "switch",
            defaultValue: false,
            showWhen: networkIs("xhttp"),
            description: "仅控制是否展开 XMUX 子字段；不会写入 xray 线协议。",
          },
          {
            key: "streamSettings.xhttpSettings.xmux.maxConcurrency",
            label: "XMUX 最大并发范围",
            control: "text",
            defaultValue: "16-32",
            placeholder: "16-32",
            showWhen: all(networkIs("xhttp"), { field: "streamSettings.xhttpSettings.enableXmux", equals: true }),
          },
          {
            key: "streamSettings.xhttpSettings.xmux.maxConnections",
            label: "XMUX 最大连接数",
            control: "number",
            defaultValue: 0,
            placeholder: "0",
            showWhen: all(networkIs("xhttp"), { field: "streamSettings.xhttpSettings.enableXmux", equals: true }),
            description: "与 maxConcurrency 互斥；非零时采用固定连接数策略。",
          },
          {
            key: "streamSettings.xhttpSettings.xmux.cMaxReuseTimes",
            label: "XMUX 连接复用次数",
            control: "number",
            defaultValue: 0,
            showWhen: all(networkIs("xhttp"), { field: "streamSettings.xhttpSettings.enableXmux", equals: true }),
          },
          {
            key: "streamSettings.xhttpSettings.xmux.hMaxRequestTimes",
            label: "XMUX 最大请求次数",
            control: "text",
            defaultValue: "600-900",
            placeholder: "600-900",
            showWhen: all(networkIs("xhttp"), { field: "streamSettings.xhttpSettings.enableXmux", equals: true }),
          },
          {
            key: "streamSettings.xhttpSettings.xmux.hMaxReusableSecs",
            label: "XMUX 最大复用秒数",
            control: "text",
            defaultValue: "1800-3000",
            placeholder: "1800-3000",
            showWhen: all(networkIs("xhttp"), { field: "streamSettings.xhttpSettings.enableXmux", equals: true }),
          },
          {
            key: "streamSettings.xhttpSettings.xmux.hKeepAlivePeriod",
            label: "XMUX Keepalive 周期",
            control: "number",
            defaultValue: 0,
            showWhen: all(networkIs("xhttp"), { field: "streamSettings.xhttpSettings.enableXmux", equals: true }),
          },
        ],
      },
      {
        id: "hysteria",
        title: "Hysteria 专用传输",
        fields: [
          {
            key: "streamSettings.hysteriaSettings.version",
            label: "版本",
            control: "number",
            defaultValue: 2,
            showWhen: protocolIs("hysteria"),
            description: "本地 3X-UI 入站表单固定使用 Hysteria 2。",
          },
          {
            key: "streamSettings.hysteriaSettings.auth",
            label: "旧版认证字段",
            control: "text",
            placeholder: "留空",
            showWhen: protocolIs("hysteria"),
            description: "保留 schema 中的 auth 字段；当前入站表单不把它当作 XBoard 用户认证。",
          },
          {
            key: "streamSettings.hysteriaSettings.udpIdleTimeout",
            label: "UDP 空闲超时（秒）",
            control: "number",
            placeholder: "2–600",
            showWhen: protocolIs("hysteria"),
          },
          {
            key: "streamSettings.hysteriaSettings.masquerade",
            label: "Masquerade 对象",
            control: "code",
            placeholder: '{"type":"proxy","url":"https://example.com","rewriteHost":false,"insecure":false}',
            rows: 4,
            showWhen: protocolIs("hysteria"),
            description: "可选对象；type 为空时使用默认 404，其他字段均位于同一对象下。",
          },
          {
            key: "streamSettings.hysteriaSettings.masquerade.type",
            label: "Masquerade 类型",
            control: "select",
            options: HYSTERIA_MASQUERADE_OPTIONS,
            showWhen: protocolIs("hysteria"),
            description: "空值、proxy、file、string；这是协议伪装目标，不是 XBoard 分享地址策略。",
          },
          {
            key: "streamSettings.hysteriaSettings.masquerade.url",
            label: "Masquerade 代理 URL",
            control: "text",
            placeholder: "https://example.com",
            showWhen: all(protocolIs("hysteria"), { field: "streamSettings.hysteriaSettings.masquerade.type", equals: "proxy" }),
          },
          {
            key: "streamSettings.hysteriaSettings.masquerade.rewriteHost",
            label: "Masquerade 重写 Host",
            control: "switch",
            defaultValue: false,
            showWhen: all(protocolIs("hysteria"), { field: "streamSettings.hysteriaSettings.masquerade.type", equals: "proxy" }),
          },
          {
            key: "streamSettings.hysteriaSettings.masquerade.insecure",
            label: "Masquerade 忽略证书",
            control: "switch",
            defaultValue: false,
            showWhen: all(protocolIs("hysteria"), { field: "streamSettings.hysteriaSettings.masquerade.type", equals: "proxy" }),
          },
          {
            key: "streamSettings.hysteriaSettings.masquerade.dir",
            label: "Masquerade 文件目录",
            control: "text",
            placeholder: "/var/www/html",
            showWhen: all(protocolIs("hysteria"), { field: "streamSettings.hysteriaSettings.masquerade.type", equals: "file" }),
          },
          {
            key: "streamSettings.hysteriaSettings.masquerade.statusCode",
            label: "Masquerade 状态码",
            control: "number",
            defaultValue: 200,
            showWhen: all(protocolIs("hysteria"), { field: "streamSettings.hysteriaSettings.masquerade.type", equals: "string" }),
          },
          {
            key: "streamSettings.hysteriaSettings.masquerade.content",
            label: "Masquerade 内容",
            control: "textarea",
            placeholder: "响应正文",
            rows: 4,
            showWhen: all(protocolIs("hysteria"), { field: "streamSettings.hysteriaSettings.masquerade.type", equals: "string" }),
          },
          {
            key: "streamSettings.hysteriaSettings.masquerade.headers",
            label: "Masquerade 响应头",
            control: "code",
            placeholder: '{"Content-Type":"text/plain"}',
            rows: 3,
            showWhen: all(protocolIs("hysteria"), { field: "streamSettings.hysteriaSettings.masquerade.type", equals: "string" }),
          },
        ],
      },
    ],
  },
  {
    id: "security",
    title: "TLS / REALITY",
    description: "安全层只跟随协议与传输能力出现；这里的 SNI、证书和密钥属于运行时配置，不是分享地址策略。",
    sections: [
      {
        id: "security-selector",
        title: "安全层选择",
        fields: [
          {
            key: "streamSettings.security",
            label: "安全层（VMess / Shadowsocks）",
            control: "select",
            options: [
              { value: "none", label: "无" },
              { value: "tls", label: "TLS" },
            ],
            showWhen: all(tlsProtocol, { field: "protocol", notEquals: ["vless", "trojan"] }, networkIn(["tcp", "ws", "http", "grpc", "httpupgrade", "xhttp"])),
            description: "TLS 可用于 VMess 与 Shadowsocks；REALITY 不属于这两个协议的可用安全层。",
          },
          {
            key: "streamSettings.security",
            label: "安全层（VLESS / Trojan：TLS / REALITY）",
            control: "select",
            options: SECURITY_OPTIONS,
            showWhen: all(realityProtocol, networkIn(["tcp", "http", "grpc", "xhttp"])),
            description: "VLESS/Trojan 在通用 TLS 传输上支持 TLS；REALITY 仅在 TCP、HTTP、gRPC、XHTTP 时可选。",
          },
          {
            key: "streamSettings.security",
            label: "安全层（VLESS / Trojan：TLS）",
            control: "select",
            options: [
              { value: "none", label: "无" },
              { value: "tls", label: "TLS" },
            ],
            showWhen: all(realityProtocol, networkIn(["ws", "httpupgrade"])),
            description: "WebSocket 与 HTTPUpgrade 可使用 TLS，但 3X-UI 不提供 REALITY 选项。",
          },
          {
            key: "streamSettings.security",
            label: "Hysteria 安全层",
            control: "select",
            options: TLS_ONLY_OPTIONS,
            showWhen: protocolIs("hysteria"),
            description: "Hysteria 入站表单只允许 TLS；WireGuard、Tunnel、TUN、HTTP、Mixed、MTProto、AmneziaWG 不显示此安全层。",
          },
        ],
      },
      {
        id: "tls",
        title: "TLS",
        fields: [
          {
            key: "streamSettings.tlsSettings.serverName",
            label: "SNI",
            control: "text",
            placeholder: "example.com",
            showWhen: all(securityIs("tls"), protocolIn(["vmess", "vless", "trojan", "shadowsocks", "hysteria"])),
          },
          {
            key: "streamSettings.tlsSettings.cipherSuites",
            label: "Cipher Suites",
            control: "multiselect",
            options: TLS_CIPHER_OPTIONS,
            showWhen: all(securityIs("tls"), protocolIn(["vmess", "vless", "trojan", "shadowsocks", "hysteria"])),
            description: "空值为自动；其余值对应 Go/Xray TLS cipher suite 名称。",
          },
          {
            key: "streamSettings.tlsSettings.minVersion",
            label: "TLS 最低版本",
            control: "select",
            options: TLS_VERSION_OPTIONS,
            showWhen: all(securityIs("tls"), protocolIn(["vmess", "vless", "trojan", "shadowsocks", "hysteria"])),
          },
          {
            key: "streamSettings.tlsSettings.maxVersion",
            label: "TLS 最高版本",
            control: "select",
            options: TLS_VERSION_OPTIONS,
            showWhen: all(securityIs("tls"), protocolIn(["vmess", "vless", "trojan", "shadowsocks", "hysteria"])),
          },
          {
            key: "streamSettings.tlsSettings.settings.fingerprint",
            label: "uTLS 指纹",
            control: "select",
            options: [{ value: "", label: "无" }, ...UTLS_OPTIONS],
            showWhen: all(securityIs("tls"), protocolIn(["vmess", "vless", "trojan", "shadowsocks", "hysteria"])),
          },
          {
            key: "streamSettings.tlsSettings.alpn",
            label: "ALPN",
            control: "multiselect",
            options: ALPN_OPTIONS,
            showWhen: all(securityIs("tls"), protocolIn(["vmess", "vless", "trojan", "shadowsocks", "hysteria"])),
          },
          {
            key: "streamSettings.tlsSettings.curvePreferences",
            label: "曲线偏好",
            control: "tags",
            options: CURVE_OPTIONS,
            placeholder: "X25519,P-256",
            showWhen: all(securityIs("tls"), protocolIn(["vmess", "vless", "trojan", "shadowsocks", "hysteria"])),
          },
          {
            key: "streamSettings.tlsSettings.rejectUnknownSni",
            label: "拒绝未知 SNI",
            control: "switch",
            defaultValue: false,
            showWhen: all(securityIs("tls"), protocolIn(["vmess", "vless", "trojan", "shadowsocks", "hysteria"])),
          },
          {
            key: "streamSettings.tlsSettings.disableSystemRoot",
            label: "禁用系统根证书",
            control: "switch",
            defaultValue: false,
            showWhen: all(securityIs("tls"), protocolIn(["vmess", "vless", "trojan", "shadowsocks", "hysteria"])),
          },
          {
            key: "streamSettings.tlsSettings.enableSessionResumption",
            label: "启用会话恢复",
            control: "switch",
            defaultValue: false,
            showWhen: all(securityIs("tls"), protocolIn(["vmess", "vless", "trojan", "shadowsocks", "hysteria"])),
          },
          {
            key: "streamSettings.tlsSettings.certificates",
            label: "证书集合",
            control: "code",
            placeholder: '[{"useFile":true,"certificateFile":"/path/fullchain.pem","keyFile":"/path/privkey.pem","certificate":[],"key":[],"ocspStapling":0,"oneTimeLoading":false,"usage":"encipherment","buildChain":false}]',
            rows: 6,
            sensitive: true,
            showWhen: all(securityIs("tls"), protocolIn(["vmess", "vless", "trojan", "shadowsocks", "hysteria"])),
            description: "每个证书项支持 useFile、certificateFile/keyFile 或 inline certificate/key、ocspStapling、oneTimeLoading、usage；usage=issue 时可设置 buildChain。",
          },
          {
            key: "streamSettings.tlsSettings.certificates[].usage",
            label: "证书用途",
            control: "select",
            options: TLS_USAGE_OPTIONS,
            defaultValue: "encipherment",
            showWhen: all(securityIs("tls"), protocolIn(["vmess", "vless", "trojan", "shadowsocks", "hysteria"])),
            description: "证书数组行的用途；issue 行还可配 buildChain。",
          },
          {
            key: "streamSettings.tlsSettings.masterKeyLog",
            label: "TLS Master Key Log",
            control: "text",
            placeholder: "/path/to/sslkeylog.txt",
            showWhen: all(securityIs("tls"), protocolIn(["vmess", "vless", "trojan", "shadowsocks", "hysteria"])),
            description: "用于调试 TLS 握手的 key log 文件路径。",
          },
          {
            key: "streamSettings.tlsSettings.echServerKeys",
            label: "ECH 服务端密钥",
            control: "text",
            sensitive: true,
            showWhen: all(securityIs("tls"), protocolIn(["vmess", "vless", "trojan", "shadowsocks", "hysteria"])),
          },
          {
            key: "streamSettings.tlsSettings.settings.echConfigList",
            label: "ECH 配置列表",
            control: "text",
            sensitive: true,
            showWhen: all(securityIs("tls"), protocolIn(["vmess", "vless", "trojan", "shadowsocks", "hysteria"])),
          },
          {
            key: "streamSettings.tlsSettings.settings.pinnedPeerCertSha256",
            label: "固定对端证书 SHA-256",
            control: "tags",
            placeholder: "每项一个 SHA-256 指纹",
            showWhen: all(securityIs("tls"), protocolIn(["vmess", "vless", "trojan", "shadowsocks", "hysteria"])),
          },
          {
            key: "streamSettings.tlsSettings.settings.verifyPeerCertByName",
            label: "按名称校验对端证书",
            control: "text",
            placeholder: "example.com",
            showWhen: all(securityIs("tls"), protocolIn(["vmess", "vless", "trojan", "shadowsocks", "hysteria"])),
          },
          {
            key: "streamSettings.tlsSettings.echSockopt",
            label: "ECH 拨号 Sockopt",
            control: "code",
            placeholder: '{"dialerProxy":"","domainStrategy":"AsIs","tcpFastOpen":false,"tcpMptcp":false}',
            rows: 4,
            showWhen: all(securityIs("tls"), protocolIn(["vmess", "vless", "trojan", "shadowsocks", "hysteria"])),
            description: "可选对象；子字段为 dialerProxy、domainStrategy、tcpFastOpen、tcpMptcp。",
          },
          {
            key: "streamSettings.tlsSettings.echSockopt.dialerProxy",
            label: "ECH 拨号代理标签",
            control: "text",
            showWhen: all(securityIs("tls"), protocolIn(["vmess", "vless", "trojan", "shadowsocks", "hysteria"])),
          },
          {
            key: "streamSettings.tlsSettings.echSockopt.domainStrategy",
            label: "ECH 域名策略",
            control: "select",
            options: DOMAIN_STRATEGY_OPTIONS,
            showWhen: all(securityIs("tls"), protocolIn(["vmess", "vless", "trojan", "shadowsocks", "hysteria"])),
          },
          {
            key: "streamSettings.tlsSettings.echSockopt.tcpFastOpen",
            label: "ECH TCP Fast Open",
            control: "switch",
            defaultValue: false,
            showWhen: all(securityIs("tls"), protocolIn(["vmess", "vless", "trojan", "shadowsocks", "hysteria"])),
          },
          {
            key: "streamSettings.tlsSettings.echSockopt.tcpMptcp",
            label: "ECH TCP MPTCP",
            control: "switch",
            defaultValue: false,
            showWhen: all(securityIs("tls"), protocolIn(["vmess", "vless", "trojan", "shadowsocks", "hysteria"])),
          },
        ],
      },
      {
        id: "reality",
        title: "REALITY",
        fields: [
          {
            key: "streamSettings.realitySettings.show",
            label: "显示 REALITY",
            control: "switch",
            defaultValue: false,
            showWhen: all(securityIs("reality"), realityProtocol, networkIn(["tcp", "http", "grpc", "xhttp"])),
          },
          {
            key: "streamSettings.realitySettings.xver",
            label: "回落版本",
            control: "number",
            defaultValue: 0,
            showWhen: all(securityIs("reality"), realityProtocol, networkIn(["tcp", "http", "grpc", "xhttp"])),
          },
          {
            key: "streamSettings.realitySettings.target",
            label: "目标站点",
            control: "text",
            placeholder: "example.com:443",
            showWhen: all(securityIs("reality"), realityProtocol, networkIn(["tcp", "http", "grpc", "xhttp"])),
            description: "REALITY 偷渡目标；target 与旧配置中的 dest 是同义兼容字段。",
          },
          {
            key: "streamSettings.realitySettings.serverNames",
            label: "服务端 SNI 集合",
            control: "tags",
            placeholder: "example.com",
            showWhen: all(securityIs("reality"), realityProtocol, networkIn(["tcp", "http", "grpc", "xhttp"])),
          },
          {
            key: "streamSettings.realitySettings.maxTimediff",
            label: "最大时间差（毫秒）",
            control: "number",
            defaultValue: 0,
            showWhen: all(securityIs("reality"), realityProtocol, networkIn(["tcp", "http", "grpc", "xhttp"])),
          },
          {
            key: "streamSettings.realitySettings.minClientVer",
            label: "最低客户端版本",
            control: "text",
            placeholder: "26.3.27",
            showWhen: all(securityIs("reality"), realityProtocol, networkIn(["tcp", "http", "grpc", "xhttp"])),
          },
          {
            key: "streamSettings.realitySettings.maxClientVer",
            label: "最高客户端版本",
            control: "text",
            placeholder: "x.y.z",
            showWhen: all(securityIs("reality"), realityProtocol, networkIn(["tcp", "http", "grpc", "xhttp"])),
          },
          {
            key: "streamSettings.realitySettings.shortIds",
            label: "Short ID 集合",
            control: "tags",
            placeholder: "每项十六进制 ID",
            showWhen: all(securityIs("reality"), realityProtocol, networkIn(["tcp", "http", "grpc", "xhttp"])),
          },
          {
            key: "streamSettings.realitySettings.settings.fingerprint",
            label: "客户端 uTLS 指纹",
            control: "select",
            options: UTLS_OPTIONS,
            defaultValue: "chrome",
            showWhen: all(securityIs("reality"), realityProtocol, networkIn(["tcp", "http", "grpc", "xhttp"])),
          },
          {
            key: "streamSettings.realitySettings.settings.serverName",
            label: "客户端 SNI",
            control: "text",
            placeholder: "example.com",
            showWhen: all(securityIs("reality"), realityProtocol, networkIn(["tcp", "http", "grpc", "xhttp"])),
          },
          {
            key: "streamSettings.realitySettings.settings.spiderX",
            label: "SpiderX 路径",
            control: "text",
            defaultValue: "/",
            placeholder: "/",
            showWhen: all(securityIs("reality"), realityProtocol, networkIn(["tcp", "http", "grpc", "xhttp"])),
          },
          {
            key: "streamSettings.realitySettings.settings.publicKey",
            label: "REALITY 公钥",
            control: "code",
            sensitive: true,
            placeholder: "Base64 公钥",
            rows: 2,
            showWhen: all(securityIs("reality"), realityProtocol, networkIn(["tcp", "http", "grpc", "xhttp"])),
          },
          {
            key: "streamSettings.realitySettings.privateKey",
            label: "REALITY 私钥",
            control: "code",
            sensitive: true,
            placeholder: "Base64 私钥",
            rows: 2,
            showWhen: all(securityIs("reality"), realityProtocol, networkIn(["tcp", "http", "grpc", "xhttp"])),
          },
          {
            key: "streamSettings.realitySettings.mldsa65Seed",
            label: "ML-DSA-65 种子",
            control: "code",
            sensitive: true,
            rows: 3,
            showWhen: all(securityIs("reality"), realityProtocol, networkIn(["tcp", "http", "grpc", "xhttp"])),
          },
          {
            key: "streamSettings.realitySettings.settings.mldsa65Verify",
            label: "ML-DSA-65 校验值",
            control: "code",
            sensitive: true,
            rows: 3,
            showWhen: all(securityIs("reality"), realityProtocol, networkIn(["tcp", "http", "grpc", "xhttp"])),
          },
          {
            key: "streamSettings.realitySettings.masterKeyLog",
            label: "REALITY Master Key Log",
            control: "text",
            placeholder: "/path/to/sslkeylog.txt",
            showWhen: all(securityIs("reality"), realityProtocol, networkIn(["tcp", "http", "grpc", "xhttp"])),
          },
          {
            key: "streamSettings.realitySettings.limitFallbackUpload",
            label: "回落上行限速",
            control: "code",
            placeholder: '{"afterBytes":0,"bytesPerSec":0,"burstBytesPerSec":0}',
            rows: 3,
            showWhen: all(securityIs("reality"), realityProtocol, networkIn(["tcp", "http", "grpc", "xhttp"])),
            description: "对象字段为 afterBytes、bytesPerSec、burstBytesPerSec；0 表示不设置该限制。",
          },
          {
            key: "streamSettings.realitySettings.limitFallbackDownload",
            label: "回落下行限速",
            control: "code",
            placeholder: '{"afterBytes":0,"bytesPerSec":0,"burstBytesPerSec":0}',
            rows: 3,
            showWhen: all(securityIs("reality"), realityProtocol, networkIn(["tcp", "http", "grpc", "xhttp"])),
            description: "对象字段为 afterBytes、bytesPerSec、burstBytesPerSec；0 表示不设置该限制。",
          },
        ],
      },
    ],
  },
  {
    id: "sniffing",
    title: "嗅探",
    description: "嗅探字段只在 3X-UI 支持的入站协议上展示；MTProto 与 AmneziaWG 的核心能力不提供这组开关。",
    sections: [
      {
        id: "sniffing-options",
        title: "协议识别",
        fields: [
          {
            key: "sniffing.enabled",
            label: "启用嗅探",
            control: "switch",
            defaultValue: false,
            showWhen: protocolNot(["mtproto", "amneziawg"]),
            description: "识别 HTTP、TLS、QUIC 或 FakeDNS 目标，以便路由层使用。",
          },
          {
            key: "sniffing.destOverride",
            label: "目标覆盖类型",
            control: "multiselect",
            options: SNIFFING_DEST_OPTIONS,
            showWhen: all(protocolNot(["mtproto", "amneziawg"]), { field: "sniffing.enabled", equals: true }),
            description: "可多选 http、tls、quic、fakedns；顺序由运行时保留。",
          },
          {
            key: "sniffing.metadataOnly",
            label: "仅元数据",
            control: "switch",
            defaultValue: false,
            showWhen: all(protocolNot(["mtproto", "amneziawg"]), { field: "sniffing.enabled", equals: true }),
            description: "只读取识别所需元数据，不主动改写目标。",
          },
          {
            key: "sniffing.routeOnly",
            label: "仅用于路由",
            control: "switch",
            defaultValue: false,
            showWhen: all(protocolNot(["mtproto", "amneziawg"]), { field: "sniffing.enabled", equals: true }),
          },
          {
            key: "sniffing.ipsExcluded",
            label: "排除 IP",
            control: "tags",
            placeholder: "IP/CIDR/geoip:*/ext:*",
            showWhen: all(protocolNot(["mtproto", "amneziawg"]), { field: "sniffing.enabled", equals: true }),
            description: "支持 IP、CIDR 以及 geoip/ext 规则字符串。",
          },
          {
            key: "sniffing.domainsExcluded",
            label: "排除域名",
            control: "tags",
            placeholder: "domain:*/ext:*",
            showWhen: all(protocolNot(["mtproto", "amneziawg"]), { field: "sniffing.enabled", equals: true }),
            description: "支持 domain 与 ext 规则字符串。",
          },
        ],
      },
    ],
  },
  {
    id: "advanced",
    title: "高级运行时",
    description: "覆盖 3X-UI 的 sockopt、FinalMask、QUIC 参数和原始 JSON 入口；只保留 Xray 运行时对象，不引入 XBoard 业务字段。",
    sections: [
      {
        id: "sockopt",
        title: "Sockopt",
        fields: [
          {
            key: "streamSettings.sockopt",
            label: "Sockopt 对象",
            control: "code",
            placeholder: '{"mark":0,"tcpFastOpen":false,"tproxy":"off","domainStrategy":"AsIs"}',
            rows: 4,
            showWhen: streamProtocol,
            description: "可选对象；下方列出 3X-UI 表单直接编辑的字段。UI 中的“真实客户端 IP”预设只是写入这些字段的快捷方式，不是线协议字段。",
          },
          {
            key: "streamSettings.sockopt.mark",
            label: "路由 Mark",
            control: "number",
            defaultValue: 0,
            showWhen: streamProtocol,
          },
          {
            key: "streamSettings.sockopt.tcpKeepAliveInterval",
            label: "TCP Keepalive 间隔",
            control: "number",
            defaultValue: 0,
            showWhen: streamProtocol,
          },
          {
            key: "streamSettings.sockopt.tcpKeepAliveIdle",
            label: "TCP Keepalive 空闲",
            control: "number",
            defaultValue: 0,
            showWhen: streamProtocol,
          },
          {
            key: "streamSettings.sockopt.tcpMaxSeg",
            label: "TCP 最大分段",
            control: "number",
            defaultValue: 0,
            showWhen: streamProtocol,
          },
          {
            key: "streamSettings.sockopt.tcpUserTimeout",
            label: "TCP 用户超时",
            control: "number",
            defaultValue: 0,
            showWhen: streamProtocol,
          },
          {
            key: "streamSettings.sockopt.tcpWindowClamp",
            label: "TCP 窗口上限",
            control: "number",
            defaultValue: 0,
            showWhen: streamProtocol,
          },
          {
            key: "streamSettings.sockopt.acceptProxyProtocol",
            label: "Sockopt PROXY Protocol",
            control: "switch",
            defaultValue: false,
            showWhen: streamProtocol,
            description: "与 TCP、WebSocket、HTTPUpgrade 自身的 acceptProxyProtocol 字段并列；最终是否生效取决于传输层。",
          },
          {
            key: "streamSettings.sockopt.tcpFastOpen",
            label: "TCP Fast Open",
            control: "switch",
            defaultValue: false,
            showWhen: streamProtocol,
          },
          {
            key: "streamSettings.sockopt.tcpMptcp",
            label: "TCP MPTCP",
            control: "switch",
            defaultValue: false,
            showWhen: streamProtocol,
          },
          {
            key: "streamSettings.sockopt.penetrate",
            label: "穿透模式",
            control: "switch",
            defaultValue: false,
            showWhen: streamProtocol,
          },
          {
            key: "streamSettings.sockopt.V6Only",
            label: "仅 IPv6",
            control: "switch",
            defaultValue: false,
            showWhen: streamProtocol,
          },
          {
            key: "streamSettings.sockopt.tcpcongestion",
            label: "TCP 拥塞控制",
            control: "select",
            options: TCP_CONGESTION_OPTIONS,
            showWhen: streamProtocol,
          },
          {
            key: "streamSettings.sockopt.tproxy",
            label: "TProxy 模式",
            control: "select",
            options: [
              { value: "off", label: "关闭" },
              { value: "redirect", label: "Redirect" },
              { value: "tproxy", label: "TProxy" },
            ],
            defaultValue: "off",
            showWhen: streamProtocol,
          },
          {
            key: "streamSettings.sockopt.domainStrategy",
            label: "域名解析策略",
            control: "select",
            options: DOMAIN_STRATEGY_OPTIONS,
            defaultValue: "AsIs",
            showWhen: streamProtocol,
          },
          {
            key: "streamSettings.sockopt.dialerProxy",
            label: "拨号代理标签",
            control: "text",
            placeholder: "出站或链式标签",
            showWhen: streamProtocol,
          },
          {
            key: "streamSettings.sockopt.interface",
            label: "绑定网卡",
            control: "text",
            placeholder: "eth0",
            showWhen: streamProtocol,
          },
          {
            key: "streamSettings.sockopt.trustedXForwardedFor",
            label: "可信 X-Forwarded-For 头",
            control: "tags",
            options: [
              { value: "CF-Connecting-IP", label: "CF-Connecting-IP" },
              { value: "X-Real-IP", label: "X-Real-IP" },
              { value: "True-Client-IP", label: "True-Client-IP" },
              { value: "X-Client-IP", label: "X-Client-IP" },
            ],
            placeholder: "CF-Connecting-IP",
            showWhen: streamProtocol,
            description: "仅 ws、httpupgrade、xhttp、grpc 等传输会读取相应可信头；不会凭空改变客户端业务归属。",
          },
          {
            key: "streamSettings.sockopt.addressPortStrategy",
            label: "地址/端口策略",
            control: "select",
            options: ADDRESS_PORT_STRATEGY_OPTIONS,
            defaultValue: "none",
            showWhen: streamProtocol,
          },
          {
            key: "streamSettings.sockopt.happyEyeballs",
            label: "Happy Eyeballs 参数",
            control: "code",
            placeholder: '{"tryDelayMs":250,"prioritizeIPv6":false,"interleave":1,"maxConcurrentTry":4}',
            rows: 4,
            showWhen: streamProtocol,
            description: "可选对象；字段为 tryDelayMs、prioritizeIPv6、interleave、maxConcurrentTry。",
          },
          {
            key: "streamSettings.sockopt.happyEyeballs.tryDelayMs",
            label: "Happy Eyeballs 延迟（毫秒）",
            control: "number",
            defaultValue: 250,
            showWhen: streamProtocol,
          },
          {
            key: "streamSettings.sockopt.happyEyeballs.prioritizeIPv6",
            label: "优先 IPv6",
            control: "switch",
            defaultValue: false,
            showWhen: streamProtocol,
          },
          {
            key: "streamSettings.sockopt.happyEyeballs.interleave",
            label: "地址交错数",
            control: "number",
            defaultValue: 1,
            showWhen: streamProtocol,
          },
          {
            key: "streamSettings.sockopt.happyEyeballs.maxConcurrentTry",
            label: "最大并发尝试",
            control: "number",
            defaultValue: 4,
            showWhen: streamProtocol,
          },
          {
            key: "streamSettings.sockopt.customSockopt",
            label: "自定义 Socket 选项",
            control: "code",
            placeholder: '[{"system":"linux","type":"int","level":"6","opt":"TCP_USER_TIMEOUT","value":10000}]',
            rows: 5,
            showWhen: streamProtocol,
            description: "每行支持 system（linux/windows/darwin）、type（int/str）、level、opt、value。",
          },
        ],
      },
      {
        id: "finalmask-tcp",
        title: "FinalMask TCP",
        fields: [
          {
            key: "streamSettings.finalmask.tcp",
            label: "TCP 掩码集合",
            control: "code",
            placeholder: '[{"type":"fragment","settings":{"packets":"1-3","lengths":["100-200"],"delays":[],"maxSplit":""}}]',
            rows: 6,
            showWhen: all(streamProtocol, networkIn(["tcp", "ws", "grpc", "httpupgrade", "xhttp"])),
            description: "每个项由 type 与多态 settings 组成；空集合表示不启用 TCP FinalMask。",
          },
          {
            key: "streamSettings.finalmask.tcp[].type",
            label: "TCP 掩码类型",
            control: "select",
            options: TCP_FINAL_MASK_OPTIONS,
            showWhen: all(streamProtocol, networkIn(["tcp", "ws", "grpc", "httpupgrade", "xhttp"])),
          },
          {
            key: "streamSettings.finalmask.tcp[].settings",
            label: "TCP 掩码参数",
            control: "code",
            placeholder: '{"packets":"1-3","lengths":["100-200"],"delays":[],"maxSplit":""}',
            rows: 5,
            showWhen: all(streamProtocol, networkIn(["tcp", "ws", "grpc", "httpupgrade", "xhttp"])),
            description: "fragment 支持 packets、lengths、delays、maxSplit；sudoku 支持 password/ascii/customTable/customTables/paddingMin/paddingMax；header-custom 支持 clients/servers；xmc 支持 hostname/profiles/password。",
          },
        ],
      },
      {
        id: "finalmask-udp",
        title: "FinalMask UDP",
        fields: [
          {
            key: "streamSettings.finalmask.udp",
            label: "Hysteria UDP 掩码集合",
            control: "code",
            placeholder: '[{"type":"salamander","settings":{"password":"secret"}}]',
            rows: 4,
            showWhen: protocolIs("hysteria"),
            description: "Hysteria 入站可使用 salamander；可选 gecko packetSize 由实现保留在 settings。",
          },
          {
            key: "streamSettings.finalmask.udp[].type",
            label: "Hysteria UDP 掩码类型",
            control: "select",
            options: HYSTERIA_FINAL_MASK_OPTIONS,
            showWhen: protocolIs("hysteria"),
          },
          {
            key: "streamSettings.finalmask.udp[].settings",
            label: "Hysteria UDP 掩码参数",
            control: "code",
            placeholder: '{"password":"secret","packetSize":"512-1200"}',
            rows: 3,
            sensitive: true,
            showWhen: protocolIs("hysteria"),
          },
          {
            key: "streamSettings.finalmask.udp",
            label: "WireGuard UDP 掩码集合",
            control: "code",
            placeholder: '[{"type":"salamander","settings":{"password":"secret"}}]',
            rows: 4,
            showWhen: protocolIs("wireguard"),
            description: "WireGuard 入站只显示 salamander UDP 掩码。",
          },
          {
            key: "streamSettings.finalmask.udp[].type",
            label: "WireGuard UDP 掩码类型",
            control: "select",
            options: WIREGUARD_FINAL_MASK_OPTIONS,
            showWhen: protocolIs("wireguard"),
          },
          {
            key: "streamSettings.finalmask.udp[].settings",
            label: "WireGuard UDP 掩码参数",
            control: "code",
            placeholder: '{"password":"secret"}',
            rows: 3,
            sensitive: true,
            showWhen: protocolIs("wireguard"),
          },
          {
            key: "streamSettings.finalmask.udp",
            label: "mKCP UDP 掩码集合",
            control: "code",
            placeholder: '[{"type":"mkcp-legacy","settings":{"header":"dns","value":""}}]',
            rows: 5,
            showWhen: networkIs("kcp"),
            description: "mKCP 可用 mkcp-legacy、xdns、xicmp、realm、header-custom、noise；具体 settings 形状随 type 变化。",
          },
          {
            key: "streamSettings.finalmask.udp[].type",
            label: "mKCP UDP 掩码类型",
            control: "select",
            options: KCP_FINAL_MASK_OPTIONS,
            showWhen: networkIs("kcp"),
          },
          {
            key: "streamSettings.finalmask.udp[].settings",
            label: "mKCP UDP 掩码参数",
            control: "code",
            placeholder: '{"header":"dns","value":""}',
            rows: 6,
            sensitive: true,
            showWhen: networkIs("kcp"),
            description: "mkcp-legacy: header/value；xdns: domains；xicmp: dgram/ips；realm: url/stunServers/tlsConfig；header-custom: client/server；noise: reset/noise。",
          },
        ],
      },
      {
        id: "quic",
        title: "QUIC 参数",
        fields: [
          {
            key: "streamSettings.finalmask.quicParams",
            label: "QUIC 参数对象",
            control: "code",
            placeholder: '{"congestion":"bbr","maxIdleTimeout":30,"keepAlivePeriod":10}',
            rows: 4,
            showWhen: networkIn(["hysteria", "xhttp"]),
            description: "Hysteria 与 XHTTP 可选；以下字段映射到同一 quicParams 对象。",
          },
          {
            key: "streamSettings.finalmask.quicParams.congestion",
            label: "拥塞控制",
            control: "select",
            options: QUIC_CONGESTION_OPTIONS,
            defaultValue: "bbr",
            showWhen: networkIn(["hysteria", "xhttp"]),
          },
          {
            key: "streamSettings.finalmask.quicParams.bbrProfile",
            label: "BBR 配置",
            control: "select",
            options: QUIC_BBR_PROFILE_OPTIONS,
            showWhen: all(networkIn(["hysteria", "xhttp"]), {
              field: "streamSettings.finalmask.quicParams.congestion",
              equals: "bbr",
            }),
          },
          {
            key: "streamSettings.finalmask.quicParams.debug",
            label: "QUIC 调试",
            control: "switch",
            defaultValue: false,
            showWhen: networkIn(["hysteria", "xhttp"]),
          },
          {
            key: "streamSettings.finalmask.quicParams.brutalUp",
            label: "Brutal 上行带宽",
            control: "text",
            placeholder: "例如 10 Mbps",
            showWhen: all(networkIn(["hysteria", "xhttp"]), {
              field: "streamSettings.finalmask.quicParams.congestion",
              equals: ["brutal", "force-brutal"],
            }),
          },
          {
            key: "streamSettings.finalmask.quicParams.brutalDown",
            label: "Brutal 下行带宽",
            control: "text",
            placeholder: "例如 50 Mbps",
            showWhen: all(networkIn(["hysteria", "xhttp"]), {
              field: "streamSettings.finalmask.quicParams.congestion",
              equals: ["brutal", "force-brutal"],
            }),
          },
          {
            key: "streamSettings.finalmask.quicParams.udpHop",
            label: "UDP Hop",
            control: "code",
            placeholder: '{"ports":"20000-50000","interval":"5-10"}',
            rows: 3,
            showWhen: networkIn(["hysteria", "xhttp"]),
            description: "可选随机端口范围与轮换间隔，两个值都是短横线范围字符串。",
          },
          {
            key: "streamSettings.finalmask.quicParams.maxIdleTimeout",
            label: "最大空闲超时（秒）",
            control: "number",
            placeholder: "4–120",
            showWhen: networkIn(["hysteria", "xhttp"]),
          },
          {
            key: "streamSettings.finalmask.quicParams.keepAlivePeriod",
            label: "Keepalive 周期（秒）",
            control: "number",
            placeholder: "2–60",
            showWhen: networkIn(["hysteria", "xhttp"]),
          },
          {
            key: "streamSettings.finalmask.quicParams.disablePathMTUDiscovery",
            label: "禁用 Path MTU Discovery",
            control: "switch",
            defaultValue: false,
            showWhen: networkIn(["hysteria", "xhttp"]),
          },
          {
            key: "streamSettings.finalmask.quicParams.maxIncomingStreams",
            label: "最大入站流数",
            control: "number",
            placeholder: "至少 8",
            showWhen: networkIn(["hysteria", "xhttp"]),
          },
          {
            key: "streamSettings.finalmask.quicParams.initStreamReceiveWindow",
            label: "初始流接收窗口",
            control: "number",
            placeholder: "16384 或更大",
            showWhen: networkIn(["hysteria", "xhttp"]),
          },
          {
            key: "streamSettings.finalmask.quicParams.maxStreamReceiveWindow",
            label: "最大流接收窗口",
            control: "number",
            placeholder: "16384 或更大",
            showWhen: networkIn(["hysteria", "xhttp"]),
          },
          {
            key: "streamSettings.finalmask.quicParams.initConnectionReceiveWindow",
            label: "初始连接接收窗口",
            control: "number",
            placeholder: "16384 或更大",
            showWhen: networkIn(["hysteria", "xhttp"]),
          },
          {
            key: "streamSettings.finalmask.quicParams.maxConnectionReceiveWindow",
            label: "最大连接接收窗口",
            control: "number",
            placeholder: "16384 或更大",
            showWhen: networkIn(["hysteria", "xhttp"]),
          },
        ],
      },
      {
        id: "json",
        title: "原始运行时 JSON",
        fields: [
          {
            key: "settings",
            label: "协议 settings 原文",
            control: "code",
            placeholder: '{"clients":[],"fallbacks":[]}',
            rows: 8,
            sensitive: true,
            description: "用于保留目录未细化的协议扩展字段；仅写入 Xray settings。请不要放入邮箱、配额、到期或订阅业务字段。",
          },
          {
            key: "streamSettings",
            label: "streamSettings 原文",
            control: "code",
            placeholder: '{"network":"ws","security":"tls","wsSettings":{"path":"/ws"}}',
            rows: 10,
            sensitive: true,
            showWhen: streamProtocol,
            description: "用于保留 Xray 传输、安全、sockopt、FinalMask 等扩展字段；Hosts/外部代理等独立资源不在入站表单内。",
          },
          {
            key: "sniffing",
            label: "sniffing 原文",
            control: "code",
            placeholder: '{"enabled":true,"destOverride":["http","tls"]}',
            rows: 5,
            showWhen: protocolNot(["mtproto", "amneziawg"]),
            description: "仅保留运行时嗅探对象；不携带 XBoard 的分享地址、订阅排序或用户策略。",
          },
        ],
      },
    ],
  },
]

export default inboundCatalog
