import type { CatalogCondition, CatalogField, CatalogOption, CatalogTab } from "./catalog-types"

/*
 * This file is a field inventory, not a renderer. The paths intentionally use
 * the names used by the Xboard control-plane form model; `[]` means one item in
 * a repeatable array. Keeping the inventory separate lets the DK Theme/shadcn
 * surface choose its own layout and interaction language.
 *
 * The inventory was reconstructed from the local 3X-UI form/schema boundary:
 * - 3x-ui/frontend/src/schemas/api/host.ts
 * - 3x-ui/frontend/src/pages/hosts/HostFormModal.tsx
 * - 3x-ui/frontend/src/pages/hosts/json-forms/{HostMuxForm,HostSockoptForm,HostFinalMaskForm}.tsx
 * - 3x-ui/frontend/src/schemas/forms/outbound-form.ts
 * - 3x-ui/frontend/src/pages/xray/outbounds/{OutboundFormModal,protocols,transport,security}
 *
 * No implementation from 3X-UI is used here. In particular, this catalog does
 * not carry its component tree, styling, translations, or adapter code.
 */

const option = (value: string, label = value): CatalogOption => ({ value, label })
const options = (values: readonly string[]): CatalogOption[] => values.map((value) => option(value))

const protocolValues = [
  "vmess",
  "vless",
  "trojan",
  "shadowsocks",
  "socks",
  "http",
  "wireguard",
  "hysteria",
  "freedom",
  "blackhole",
  "dns",
  "loopback",
] as const

const streamProtocolValues = ["vmess", "vless", "trojan", "shadowsocks", "hysteria"] as const
const serverProtocolValues = [
  "vmess",
  "vless",
  "trojan",
  "shadowsocks",
  "socks",
  "http",
  "hysteria",
] as const

const muxProtocolValues = ["vmess", "vless", "trojan", "shadowsocks", "http", "socks"] as const
const tlsProtocolValues = ["vmess", "vless", "trojan", "shadowsocks", "hysteria"] as const
const realityProtocolValues = ["vless", "trojan"] as const

const networkValues = ["tcp", "kcp", "ws", "grpc", "httpupgrade", "xhttp"] as const
// Hysteria's transport is fixed to `hysteria`; the other entries are the
// stream networks accepted by the outbound TLS form.
const tlsNetworkValues = ["tcp", "ws", "grpc", "httpupgrade", "xhttp", "hysteria"] as const
const realityNetworkValues = ["tcp", "grpc", "xhttp"] as const

const hostSecurityOptions = [
  option("same", "跟随入站"),
  option("tls", "TLS"),
  option("none", "无"),
  option("reality", "Reality"),
]

const securityOptions = [option("none", "无"), option("tls", "TLS"), option("reality", "Reality")]
const protocolOptions = protocolValues.map((value) => option(value, value.toUpperCase()))
const networkLabels: Record<string, string> = {
  tcp: "TCP / Raw",
  kcp: "mKCP",
  ws: "WebSocket",
  grpc: "gRPC",
  httpupgrade: "HTTPUpgrade",
  xhttp: "XHTTP",
}
const networkOptions = networkValues.map((value) => option(value, networkLabels[value]))
const targetStrategyOptions = options([
  "AsIs",
  "UseIP",
  "UseIPv4",
  "UseIPv6",
  "UseIPv6v4",
  "UseIPv4v6",
  "ForceIP",
  "ForceIPv6v4",
  "ForceIPv6",
  "ForceIPv4v6",
  "ForceIPv4",
])
const vmessSecurityOptions = options(["aes-128-gcm", "chacha20-poly1305", "auto"])
const flowOptions = [
  option("", "无"),
  option("xtls-rprx-vision", "xtls-rprx-vision"),
  option("xtls-rprx-vision-udp443", "xtls-rprx-vision-udp443"),
]
const shadowsocksMethodOptions = options([
  "aes-256-gcm",
  "chacha20-poly1305",
  "chacha20-ietf-poly1305",
  "xchacha20-ietf-poly1305",
  "2022-blake3-aes-128-gcm",
  "2022-blake3-aes-256-gcm",
  "2022-blake3-chacha20-poly1305",
])
const utlsOptions = options([
  "",
  "chrome",
  "firefox",
  "safari",
  "ios",
  "android",
  "edge",
  "360",
  "qq",
  "random",
  "randomized",
  "randomizednoalpn",
  "unsafe",
])
const alpnOptions = options(["h3", "h2", "http/1.1"])
const addressPortStrategyOptions = options([
  "none",
  "SrvPortOnly",
  "SrvAddressOnly",
  "SrvPortAndAddress",
  "TxtPortOnly",
  "TxtAddressOnly",
  "TxtPortAndAddress",
])
const sockoptDomainStrategyOptions = options([
  "AsIs",
  "UseIP",
  "UseIPv6v4",
  "UseIPv6",
  "UseIPv4v6",
  "UseIPv4",
  "ForceIP",
  "ForceIPv6v4",
  "ForceIPv6",
  "ForceIPv4v6",
  "ForceIPv4",
])
const wireguardDomainStrategyOptions = options([
  "ForceIP",
  "ForceIPv4",
  "ForceIPv4v6",
  "ForceIPv6",
  "ForceIPv6v4",
])
const mihomoIpVersionOptions = options(["dual", "ipv4", "ipv6", "ipv4-prefer", "ipv6-prefer"])
const subscriptionTypeOptions = options(["raw", "json", "clash"])

const sniffingDestOptions = options(["http", "tls", "quic", "fakedns"])
const xhttpModeOptions = options(["auto", "packet-up", "stream-up", "stream-one"])
const xhttpPlacementOptions = [
  option("", "默认（path）"),
  option("path", "path"),
  option("header", "header"),
  option("cookie", "cookie"),
  option("query", "query"),
]
const xhttpPaddingPlacementOptions = [
  option("", "默认（queryInHeader）"),
  option("queryInHeader", "queryInHeader"),
  option("header", "header"),
  option("cookie", "cookie"),
  option("query", "query"),
]
const xhttpPaddingMethodOptions = [
  option("", "默认（repeat-x）"),
  option("repeat-x", "repeat-x"),
  option("tokenish", "tokenish"),
]
const xhttpUplinkMethodOptions = [
  option("", "默认（POST）"),
  option("POST", "POST"),
  option("PUT", "PUT"),
  option("GET", "GET（仅 packet-up）"),
]
const xhttpUplinkDataPlacementOptions = [
  option("", "默认（auto）"),
  option("auto", "auto"),
  option("body", "body"),
  option("header", "header"),
  option("cookie", "cookie"),
]

const when = (field: string, equals: string | string[] | boolean): CatalogCondition => ({ field, equals })
const whenNot = (field: string, notEquals: string | string[] | boolean): CatalogCondition => ({ field, notEquals })
const protocolWhen = (values: readonly string[]): CatalogCondition => when("protocol", [...values])
const networkWhen = (values: readonly string[]): CatalogCondition => when("streamSettings.network", [...values])
const allWhen = (...conditions: (CatalogCondition | CatalogCondition[])[]): CatalogCondition[] =>
  conditions.flat()

const showHostTls = when("security", ["tls", "reality"])
const showHostTlsOnly = when("security", "tls")
const showStream = protocolWhen(streamProtocolValues)
const showServer = protocolWhen(serverProtocolValues)
const showMuxProtocol = allWhen(
  protocolWhen(muxProtocolValues),
  when("settings.flow", ""),
  whenNot("streamSettings.network", "xhttp"),
)
const showTls = allWhen(protocolWhen(tlsProtocolValues), networkWhen(tlsNetworkValues))
const showReality = allWhen(protocolWhen(realityProtocolValues), networkWhen(realityNetworkValues))
const showNonHysteriaStream = protocolWhen(["vmess", "vless", "trojan", "shadowsocks"])
const showXhttp = allWhen(showStream, networkWhen(["xhttp"]))

const hostBasicFields: CatalogField[] = [
  {
    key: "remark",
    label: "主机备注",
    control: "text",
    placeholder: "例如：香港主站入口",
    description: "对应 3X-UI Host 的 remark；只用于识别该发布主机。",
  },
  {
    key: "serverDescription",
    label: "服务说明",
    control: "text",
    placeholder: "例如：面向标准组",
    description: "对应 serverDescription，供客户端/订阅展示的短说明。",
  },
  {
    key: "inboundIds",
    label: "关联入站",
    control: "multiselect",
    placeholder: "选择一个或多个运行入站",
    description: "发布主机必须绑定实际入站；值对应 HostForm 的 inboundIds。",
  },
  {
    key: "hosts",
    label: "发布地址",
    control: "tags",
    placeholder: "cdn.example.com, cdn2.example.com:443",
    description: "可填写多个地址；逗号、分号或空格分隔。不要把 XBoard 业务订阅字段混入地址。",
  },
  {
    key: "port",
    label: "发布端口",
    control: "number",
    defaultValue: 0,
    placeholder: "0 表示沿用地址或入站端口",
    description: "3X-UI 允许 0–65535；0 表示不覆盖。",
  },
  {
    key: "tags",
    label: "主机标签",
    control: "tags",
    placeholder: "例如：EDGE,HK",
    description: "3X-UI HostTag 的大写字母、数字、下划线和冒号标签；最多 10 个。",
  },
  {
    key: "nodeGuids",
    label: "节点绑定",
    control: "multiselect",
    placeholder: "选择可使用该主机的节点",
    description: "值来自节点 GUID；这是控制面绑定，不是套餐、到期或流量字段。",
  },
  {
    key: "enable",
    label: "启用主机",
    control: "switch",
    defaultValue: true,
    description: "Xboard 表单侧的 enable 会序列化为 3X-UI Host 的 isDisabled = !enable。",
  },
  {
    key: "isHidden",
    label: "从订阅隐藏",
    control: "switch",
    defaultValue: false,
    description: "对应 3X-UI isHidden；隐藏发布项仍可作为控制面记录保留。",
  },
]

const hostSecurityFields: CatalogField[] = [
  {
    key: "security",
    label: "主机安全模式",
    control: "select",
    options: hostSecurityOptions,
    defaultValue: "same",
    description: "same 继承关联入站安全；tls、reality、none 覆盖发布端安全模式。",
  },
  {
    key: "sni",
    label: "SNI",
    control: "text",
    placeholder: "edge.example.com",
    showWhen: showHostTls,
    description: "仅 TLS/Reality 发布主机使用；空值时由地址或协议默认值决定。",
  },
  {
    key: "overrideSniFromAddress",
    label: "从地址覆盖 SNI",
    control: "switch",
    defaultValue: false,
    showWhen: showHostTls,
    description: "启用后以当前发布地址作为 SNI。",
  },
  {
    key: "keepSniBlank",
    label: "保持空 SNI",
    control: "switch",
    defaultValue: false,
    showWhen: showHostTls,
    description: "与 overrideSniFromAddress 互斥；用于明确要求不发送 SNI 的端点。",
  },
  {
    key: "fingerprint",
    label: "uTLS 指纹",
    control: "select",
    options: utlsOptions,
    placeholder: "不指定",
    showWhen: showHostTls,
    description: "Host 表单在 TLS/Reality 下都允许选择；空值表示跟随客户端默认。",
  },
  {
    key: "alpn",
    label: "ALPN",
    control: "multiselect",
    options: alpnOptions,
    placeholder: "选择协商协议",
    showWhen: showHostTlsOnly,
    description: "HostForm 仅在 TLS 模式显示；可多选 h3、h2、http/1.1。",
  },
  {
    key: "pinnedPeerCertSha256",
    label: "证书 SHA-256 Pin",
    control: "tags",
    placeholder: "base64 SHA-256 指纹",
    showWhen: showHostTlsOnly,
    description: "每个 pin 是一项；空数组不覆盖上游证书校验。",
  },
  {
    key: "verifyPeerCertByName",
    label: "按名称校验证书",
    control: "text",
    placeholder: "example.com",
    showWhen: showHostTlsOnly,
    description: "对应 verifyPeerCertByName；与 SNI 分开控制证书名称校验。",
  },
  {
    key: "allowInsecure",
    label: "允许不安全证书",
    control: "switch",
    defaultValue: false,
    showWhen: showHostTlsOnly,
    description: "仅在明确需要时打开；会放宽 TLS 证书校验。",
  },
  {
    key: "echConfigList",
    label: "ECH 配置",
    control: "textarea",
    placeholder: "可选 ECH config list",
    showWhen: showHostTlsOnly,
    description: "传递给 TLS 客户端的 echConfigList。",
    rows: 3,
  },
]

const hostTransportFields: CatalogField[] = [
  {
    key: "hostHeader",
    label: "Host Header",
    control: "text",
    placeholder: "可选 HTTP Host",
    description: "发布端点的 HTTP Host 覆盖值；与安全模式独立。",
  },
  {
    key: "path",
    label: "路径",
    control: "text",
    placeholder: "/gateway",
    description: "发布端点的路径或服务名；由关联入站的传输协议解释。",
  },
  {
    key: "vlessRoute",
    label: "VLESS Route",
    control: "number",
    placeholder: "1–65535，可留空",
    description: "仅对需要 VLESS route 的发布链路生效；对应 HostForm 的 1–65535 字符串字段。",
  },
]

const hostMuxFields: CatalogField[] = [
  {
    key: "muxParams.enabled",
    label: "主机 Mux 覆盖",
    control: "switch",
    defaultValue: false,
    description: "3X-UI 将启用的覆盖保存为 muxParams JSON；关闭表示继承入站/全局 Mux。",
  },
  {
    key: "muxParams.concurrency",
    label: "Mux 并发数",
    control: "number",
    defaultValue: 8,
    placeholder: "-1 至 1024",
    showWhen: when("muxParams.enabled", true),
    description: "对应 Mux concurrency。",
  },
  {
    key: "muxParams.xudpConcurrency",
    label: "XUDP 并发数",
    control: "number",
    defaultValue: 16,
    placeholder: "-1 至 1024",
    showWhen: when("muxParams.enabled", true),
    description: "对应 Mux xudpConcurrency。",
  },
  {
    key: "muxParams.xudpProxyUDP443",
    label: "XUDP UDP/443",
    control: "select",
    options: options(["reject", "allow", "skip"]),
    defaultValue: "reject",
    showWhen: when("muxParams.enabled", true),
    description: "reject、allow、skip 三种策略；主机覆盖关闭时不写入该 JSON。",
  },
]

const hostSockoptFields: CatalogField[] = [
  {
    key: "sockoptParams.enabled",
    label: "主机 Sockopt 覆盖",
    control: "switch",
    defaultValue: false,
    description: "3X-UI 以 sockoptParams JSON 是否为空表示覆盖开关；宿主机输出会过滤入站专用键。",
  },
  {
    key: "sockoptParams.dialerProxy",
    label: "链式出站 Tag",
    control: "select",
    placeholder: "选择另一个出站 Tag",
    showWhen: when("sockoptParams.enabled", true),
    description: "通过一个出站 Tag 作为 dialerProxy；运行时应排除 balancer 与 blackhole，选项由出站目录动态注入。",
  },
  {
    key: "sockoptParams.domainStrategy",
    label: "解析策略",
    control: "select",
    options: sockoptDomainStrategyOptions,
    defaultValue: "AsIs",
    showWhen: when("sockoptParams.enabled", true),
  },
  {
    key: "sockoptParams.addressPortStrategy",
    label: "地址/端口策略",
    control: "select",
    options: addressPortStrategyOptions,
    defaultValue: "none",
    showWhen: when("sockoptParams.enabled", true),
  },
  {
    key: "sockoptParams.tcpKeepAliveInterval",
    label: "TCP Keepalive 间隔",
    control: "number",
    defaultValue: 0,
    placeholder: "秒；0 使用系统默认",
    showWhen: when("sockoptParams.enabled", true),
  },
  {
    key: "sockoptParams.tcpFastOpen",
    label: "TCP Fast Open",
    control: "switch",
    defaultValue: false,
    showWhen: when("sockoptParams.enabled", true),
  },
  {
    key: "sockoptParams.tcpMptcp",
    label: "Multipath TCP",
    control: "switch",
    defaultValue: false,
    showWhen: when("sockoptParams.enabled", true),
  },
  {
    key: "sockoptParams.penetrate",
    label: "穿透模式",
    control: "switch",
    defaultValue: false,
    showWhen: when("sockoptParams.enabled", true),
  },
  {
    key: "sockoptParams.mark",
    label: "Fwmark",
    control: "number",
    defaultValue: 0,
    placeholder: "0 表示不设置",
    showWhen: when("sockoptParams.enabled", true),
  },
  {
    key: "sockoptParams.interface",
    label: "网络接口",
    control: "text",
    placeholder: "例如：eth0",
    showWhen: when("sockoptParams.enabled", true),
  },
  {
    key: "sockoptParams.tproxy",
    label: "TProxy",
    control: "select",
    options: options(["off", "redirect", "tproxy"]),
    defaultValue: "off",
    showWhen: when("sockoptParams.enabled", true),
  },
  {
    key: "sockoptParams.tcpcongestion",
    label: "TCP 拥塞控制",
    control: "select",
    options: options(["bbr", "cubic", "reno"]),
    defaultValue: "bbr",
    showWhen: when("sockoptParams.enabled", true),
  },
  {
    key: "sockoptParams.tcpUserTimeout",
    label: "TCP 用户超时",
    control: "number",
    defaultValue: 0,
    placeholder: "毫秒；0 使用系统默认",
    showWhen: when("sockoptParams.enabled", true),
  },
  {
    key: "sockoptParams.tcpKeepAliveIdle",
    label: "TCP Keepalive 空闲",
    control: "number",
    defaultValue: 0,
    placeholder: "秒；0 使用系统默认",
    showWhen: when("sockoptParams.enabled", true),
  },
  {
    key: "sockoptParams.tcpMaxSeg",
    label: "TCP 最大分段",
    control: "number",
    defaultValue: 0,
    placeholder: "0 使用系统默认",
    showWhen: when("sockoptParams.enabled", true),
  },
  {
    key: "sockoptParams.tcpWindowClamp",
    label: "TCP Window Clamp",
    control: "number",
    defaultValue: 0,
    placeholder: "0 使用系统默认",
    showWhen: when("sockoptParams.enabled", true),
  },
  {
    key: "sockoptParams.happyEyeballs.enabled",
    label: "Happy Eyeballs",
    control: "switch",
    defaultValue: false,
    showWhen: when("sockoptParams.enabled", true),
    description: "3X-UI 通过 happyEyeballs 子对象是否存在表示开关。",
  },
  {
    key: "sockoptParams.happyEyeballs.tryDelayMs",
    label: "Happy Eyeballs 尝试延迟",
    control: "number",
    defaultValue: 250,
    placeholder: "毫秒；250 常用",
    showWhen: allWhen(when("sockoptParams.enabled", true), when("sockoptParams.happyEyeballs.enabled", true)),
  },
  {
    key: "sockoptParams.happyEyeballs.prioritizeIPv6",
    label: "优先 IPv6",
    control: "switch",
    defaultValue: false,
    showWhen: allWhen(when("sockoptParams.enabled", true), when("sockoptParams.happyEyeballs.enabled", true)),
  },
  {
    key: "sockoptParams.happyEyeballs.interleave",
    label: "地址交错数",
    control: "number",
    defaultValue: 1,
    placeholder: "至少 1",
    showWhen: allWhen(when("sockoptParams.enabled", true), when("sockoptParams.happyEyeballs.enabled", true)),
  },
  {
    key: "sockoptParams.happyEyeballs.maxConcurrentTry",
    label: "最大并发尝试",
    control: "number",
    defaultValue: 4,
    placeholder: "0 表示不限制",
    showWhen: allWhen(when("sockoptParams.enabled", true), when("sockoptParams.happyEyeballs.enabled", true)),
  },
  {
    key: "sockoptParams.customSockopt",
    label: "自定义 Socket 选项",
    control: "code",
    placeholder: '[{"system":"linux","type":"int","level":"6","opt":"1","value":1}]',
    showWhen: when("sockoptParams.enabled", true),
    description: "JSON 数组；每项包含可选 system、type、level、opt、value。",
    rows: 5,
  },
]

const finalMaskTcpTypeOptions = options(["fragment", "header-custom", "sudoku", "xmc"])
const finalMaskUdpTypeOptions = options([
  "salamander",
  "mkcp-legacy",
  "header-custom",
  "xdns",
  "xicmp",
  "noise",
  "realm",
])
const hostFinalMaskUdpTypeOptions = options([
  "mkcp-legacy",
  "header-custom",
  "xdns",
  "xicmp",
  "noise",
  "realm",
])

const hostFinalMaskFields: CatalogField[] = [
  {
    key: "finalMask.tcp",
    label: "TCP Final Mask",
    control: "code",
    placeholder: '{"tcp":[{"type":"fragment","settings":{}}]}',
    description: "HostFinalMaskForm 的 TCP mask 数组。类型：fragment、header-custom、sudoku、xmc；具体 settings 随类型变化。",
    options: finalMaskTcpTypeOptions,
    rows: 7,
  },
  {
    key: "finalMask.udp",
    label: "UDP Final Mask",
    control: "code",
    placeholder: '{"udp":[{"type":"salamander","settings":{}}]}',
    description: "HostFinalMaskForm 的 showAll UDP mask 数组。类型：mkcp-legacy、header-custom、xDNS、xICMP、noise、realm；Hysteria/WireGuard 专用 salamander 不在 Host 的通用列表中。",
    options: hostFinalMaskUdpTypeOptions,
    rows: 7,
  },
  {
    key: "finalMask.quicParams",
    label: "QUIC 参数",
    control: "code",
    placeholder: '{"congestion":"bbr","udpHop":{"ports":"20000-50000","interval":"5-10"}}',
    description: "可选 quicParams；窗口、拥塞、UDP hop 等字段由 FinalMaskForm 解释。空对象表示无 host override。",
    rows: 8,
  },
]

const hostClientFields: CatalogField[] = [
  {
    key: "excludeFromSubTypes",
    label: "排除订阅格式",
    control: "multiselect",
    options: subscriptionTypeOptions,
    placeholder: "选择不生成的格式",
    description: "这是 3X-UI 的 Host 输出兼容设置；不包含 XBoard 的套餐排序、到期或流量重置。",
  },
  {
    key: "mihomoIpVersion",
    label: "Mihomo IP 版本",
    control: "select",
    options: mihomoIpVersionOptions,
    placeholder: "跟随客户端默认",
    description: "Clash/Mihomo 输出时的地址族偏好。",
  },
  {
    key: "mihomoX25519",
    label: "Mihomo X25519",
    control: "switch",
    defaultValue: false,
    description: "对应 HostForm 的 Mihomo X25519 兼容开关。",
  },
  {
    key: "shuffleHost",
    label: "打乱主机地址",
    control: "switch",
    defaultValue: false,
    description: "在多个发布地址之间改变输出顺序；它不是 XBoard 订阅排序字段。",
  },
]

export const managedHostCatalog: CatalogTab[] = [
  {
    id: "managed-host-basic",
    title: "发布主机",
    description: "管理与入站绑定的对外地址、端口和控制面状态。",
    sections: [
      { id: "host-basic", title: "基本信息", fields: hostBasicFields },
      { id: "host-transport", title: "地址与传输覆盖", fields: hostTransportFields },
    ],
  },
  {
    id: "managed-host-security",
    title: "主机安全",
    description: "发布主机的 TLS、Reality 与证书校验覆盖。",
    sections: [{ id: "host-security", title: "安全参数", fields: hostSecurityFields }],
  },
  {
    id: "managed-host-overrides",
    title: "运行覆盖",
    description: "按主机覆盖 Mux、Sockopt 与 Final Mask；关闭开关时保持稀疏 JSON。",
    sections: [
      { id: "host-mux", title: "Mux", fields: hostMuxFields },
      { id: "host-sockopt", title: "Sockopt 与链式代理", fields: hostSockoptFields },
      { id: "host-final-mask", title: "Final Mask", fields: hostFinalMaskFields },
    ],
  },
  {
    id: "managed-host-client",
    title: "客户端输出",
    description: "保留 3X-UI 的格式排除与 Mihomo 兼容选项。",
    sections: [{ id: "host-client", title: "订阅兼容", fields: hostClientFields }],
  },
]

const outboundIdentityFields: CatalogField[] = [
  {
    key: "protocol",
    label: "协议",
    control: "select",
    options: protocolOptions,
    defaultValue: "vless",
    description: "协议改变 settings 分支、可用传输、安全、Mux 与 Final Mask。",
  },
  {
    key: "tag",
    label: "出站 Tag",
    control: "text",
    placeholder: "proxy-out",
    description: "必填且唯一；Tag 是路由和 dialerProxy 链式引用的稳定标识。",
  },
  {
    key: "sendThrough",
    label: "发送源地址",
    control: "text",
    placeholder: "0.0.0.0 或本机地址",
    description: "对应 Xray outbound sendThrough；空值表示让系统选择源地址。",
  },
  {
    key: "targetStrategy",
    label: "目标解析策略",
    control: "select",
    options: targetStrategyOptions,
    placeholder: "AsIs（不覆盖）",
    description: "AsIs、UseIP、UseIPv4/6、ForceIP 等策略；空值表示 AsIs。",
  },
]

const outboundServerFields: CatalogField[] = [
  {
    key: "settings.address",
    label: "服务器地址",
    control: "text",
    placeholder: "proxy.example.net",
    showWhen: showServer,
    description: "VMess/VLESS/Trojan/Shadowsocks/SOCKS/HTTP/Hysteria 的连接目标。",
  },
  {
    key: "settings.port",
    label: "服务器端口",
    control: "number",
    defaultValue: 443,
    placeholder: "1–65535",
    showWhen: showServer,
  },
  {
    key: "settings.id",
    label: "用户 ID",
    control: "text",
    placeholder: "UUID",
    showWhen: protocolWhen(["vmess", "vless"]),
    description: "VMess/VLESS 的 UUID。",
  },
  {
    key: "settings.security",
    label: "VMess 用户加密",
    control: "select",
    options: vmessSecurityOptions,
    defaultValue: "auto",
    showWhen: protocolWhen(["vmess"]),
  },
  {
    key: "settings.encryption",
    label: "VLESS 加密",
    control: "text",
    defaultValue: "none",
    placeholder: "none 或 vlessenc 参数",
    showWhen: protocolWhen(["vless"]),
    description: "空值会归一为 none；vlessenc/ML-KEM 值会影响 XHTTP Vision 能力。",
  },
  {
    key: "settings.reverseTag",
    label: "VLESS Reverse Tag",
    control: "text",
    placeholder: "可选入站 Tag",
    showWhen: protocolWhen(["vless"]),
    description: "填写后才启用 reverse sniffing 子配置。",
  },
  {
    key: "settings.reverseSniffing.enabled",
    label: "Reverse Sniffing",
    control: "switch",
    defaultValue: false,
    showWhen: allWhen(protocolWhen(["vless"]), whenNot("settings.reverseTag", "")),
    description: "共享 Xray SniffingConfig；reverseTag 为空时整个分支不下发。",
  },
  {
    key: "settings.reverseSniffing.destOverride",
    label: "Reverse 目标协议",
    control: "multiselect",
    options: sniffingDestOptions,
    showWhen: allWhen(
      protocolWhen(["vless"]),
      whenNot("settings.reverseTag", ""),
      when("settings.reverseSniffing.enabled", true),
    ),
  },
  {
    key: "settings.reverseSniffing.metadataOnly",
    label: "Reverse 仅元数据",
    control: "switch",
    defaultValue: false,
    showWhen: allWhen(
      protocolWhen(["vless"]),
      whenNot("settings.reverseTag", ""),
      when("settings.reverseSniffing.enabled", true),
    ),
  },
  {
    key: "settings.reverseSniffing.routeOnly",
    label: "Reverse 仅路由",
    control: "switch",
    defaultValue: false,
    showWhen: allWhen(
      protocolWhen(["vless"]),
      whenNot("settings.reverseTag", ""),
      when("settings.reverseSniffing.enabled", true),
    ),
  },
  {
    key: "settings.reverseSniffing.ipsExcluded",
    label: "Reverse 排除 IP",
    control: "tags",
    placeholder: "IP/CIDR/geoip:private",
    showWhen: allWhen(
      protocolWhen(["vless"]),
      whenNot("settings.reverseTag", ""),
      when("settings.reverseSniffing.enabled", true),
    ),
  },
  {
    key: "settings.reverseSniffing.domainsExcluded",
    label: "Reverse 排除域名",
    control: "tags",
    placeholder: "domain:example.com",
    showWhen: allWhen(
      protocolWhen(["vless"]),
      whenNot("settings.reverseTag", ""),
      when("settings.reverseSniffing.enabled", true),
    ),
  },
  {
    key: "settings.flow",
    label: "TLS Flow",
    control: "select",
    options: flowOptions,
    placeholder: "无",
    showWhen: allWhen(protocolWhen(["vless"]), networkWhen(["tcp", "xhttp"])),
    description: "3X-UI 进一步要求：TCP 仅在 TLS/Reality 下显示；XHTTP 仅在 encryption 非 none 时显示。",
  },
  {
    key: "settings.testpre",
    label: "Vision Testpre",
    control: "number",
    defaultValue: 0,
    placeholder: "0 表示默认",
    showWhen: allWhen(
      protocolWhen(["vless"]),
      when("settings.flow", "xtls-rprx-vision"),
    ),
  },
  {
    key: "settings.testseed",
    label: "Vision Testseed",
    control: "code",
    placeholder: "[900, 500, 900, 256]",
    showWhen: allWhen(protocolWhen(["vless"]), when("settings.flow", "xtls-rprx-vision")),
    description: "四个正整数；仅 xtls-rprx-vision 生效。",
  },
  {
    key: "settings.password",
    label: "密码",
    control: "password",
    placeholder: "上游凭据",
    sensitive: true,
    showWhen: protocolWhen(["trojan"]),
  },
  {
    key: "settings.password",
    label: "Shadowsocks 密钥",
    control: "password",
    placeholder: "Shadowsocks 密钥",
    sensitive: true,
    showWhen: protocolWhen(["shadowsocks"]),
  },
  {
    key: "settings.method",
    label: "Shadowsocks 加密方法",
    control: "select",
    options: shadowsocksMethodOptions,
    defaultValue: "2022-blake3-aes-128-gcm",
    showWhen: protocolWhen(["shadowsocks"]),
  },
  {
    key: "settings.uot",
    label: "UDP over TCP",
    control: "switch",
    defaultValue: false,
    showWhen: protocolWhen(["shadowsocks"]),
  },
  {
    key: "settings.UoTVersion",
    label: "UoT 版本",
    control: "number",
    defaultValue: 1,
    placeholder: "1 或 2",
    showWhen: allWhen(protocolWhen(["shadowsocks"]), when("settings.uot", true)),
  },
  {
    key: "settings.user",
    label: "代理用户名",
    control: "text",
    placeholder: "可选用户名",
    showWhen: protocolWhen(["socks", "http"]),
  },
  {
    key: "settings.pass",
    label: "代理密码",
    control: "password",
    placeholder: "可选密码",
    sensitive: true,
    showWhen: protocolWhen(["socks", "http"]),
  },
  {
    key: "settings.headers",
    label: "HTTP 代理 Headers",
    control: "code",
    placeholder: '{"Proxy-Authorization":"..."}',
    showWhen: protocolWhen(["http"]),
    description: "HTTP outbound 的 settings.headers 是字符串键值 JSON 对象。",
    rows: 4,
  },
  {
    key: "settings.address",
    label: "WireGuard 地址",
    control: "text",
    placeholder: "10.0.0.2,fd00::2",
    showWhen: protocolWhen(["wireguard"]),
    description: "WireGuard 表单以逗号连接地址数组；没有端口字段。",
  },
  {
    key: "settings.secretKey",
    label: "WireGuard 私钥",
    control: "password",
    placeholder: "base64 private key",
    sensitive: true,
    showWhen: protocolWhen(["wireguard"]),
  },
  {
    key: "settings.pubKey",
    label: "WireGuard 公钥",
    control: "text",
    placeholder: "由私钥派生",
    showWhen: protocolWhen(["wireguard"]),
    description: "只读派生值；不写入 outbound wire payload。",
  },
  {
    key: "settings.domainStrategy",
    label: "WireGuard 域名策略",
    control: "select",
    options: wireguardDomainStrategyOptions,
    placeholder: "不指定",
    showWhen: protocolWhen(["wireguard"]),
  },
  {
    key: "settings.mtu",
    label: "WireGuard MTU",
    control: "number",
    defaultValue: 1420,
    placeholder: "正整数；0 使用默认",
    showWhen: protocolWhen(["wireguard"]),
  },
  {
    key: "settings.reserved",
    label: "WireGuard Reserved",
    control: "text",
    placeholder: "逗号分隔字节，例如 1,2,3",
    showWhen: protocolWhen(["wireguard"]),
  },
  {
    key: "settings.noKernelTun",
    label: "不使用内核 TUN",
    control: "switch",
    defaultValue: false,
    showWhen: protocolWhen(["wireguard"]),
  },
  {
    key: "settings.peers",
    label: "WireGuard Peers",
    control: "code",
    placeholder: '[{"publicKey":"…","endpoint":"host:port","allowedIPs":["0.0.0.0/0"]}]',
    showWhen: protocolWhen(["wireguard"]),
    description: "每项支持 publicKey、psk（序列化为 wire 的 preSharedKey）、allowedIPs、endpoint、keepAlive；数组至少一项。",
    rows: 8,
  },
  {
    key: "settings.domainStrategy",
    label: "Freedom 域名策略",
    control: "select",
    options: targetStrategyOptions,
    placeholder: "不指定",
    showWhen: protocolWhen(["freedom"]),
  },
  {
    key: "settings.redirect",
    label: "Freedom Redirect",
    control: "text",
    placeholder: "可选目标地址",
    showWhen: protocolWhen(["freedom"]),
  },
  {
    key: "settings.userLevel",
    label: "用户等级",
    control: "number",
    defaultValue: 0,
    placeholder: "0 或更高",
    showWhen: protocolWhen(["freedom", "dns"]),
  },
  {
    key: "settings.proxyProtocol",
    label: "PROXY Protocol",
    control: "select",
    options: [option("0", "无"), option("1", "v1"), option("2", "v2")],
    defaultValue: 0,
    showWhen: protocolWhen(["freedom"]),
  },
  {
    key: "settings.fragment",
    label: "Freedom Fragment",
    control: "code",
    placeholder: '{"packets":"tlshello","length":"100-200","interval":"10-20","maxSplit":"300-400"}',
    showWhen: protocolWhen(["freedom"]),
    description: "可选 TCP 分片对象；仅有 packets 默认值不代表启用。",
    rows: 5,
  },
  {
    key: "settings.noises",
    label: "Freedom Noises",
    control: "code",
    placeholder: '[{"type":"rand","packet":"10-20","delay":"10-16","applyTo":"ip"}]',
    showWhen: protocolWhen(["freedom"]),
    description: "数组项 type 可为 rand/base64/str/hex，applyTo 可为 ip/ipv4/ipv6。",
    rows: 5,
  },
  {
    key: "settings.finalRules",
    label: "Freedom Final Rules",
    control: "code",
    placeholder: '[{"action":"block","network":"tcp","port":"80","ip":["geoip:private"]}]',
    showWhen: protocolWhen(["freedom"]),
    description: "action 为 allow/block；blockDelay 仅在 block 时有意义。",
    rows: 6,
  },
  {
    key: "settings.type",
    label: "Blackhole 响应",
    control: "select",
    options: [option("", "空（静默丢弃）"), option("none", "none"), option("http", "http")],
    placeholder: "空",
    showWhen: protocolWhen(["blackhole"]),
  },
  {
    key: "settings.rewriteNetwork",
    label: "DNS 重写网络",
    control: "select",
    options: [option("", "不改写"), option("udp", "udp"), option("tcp", "tcp")],
    placeholder: "不改写",
    showWhen: protocolWhen(["dns"]),
  },
  {
    key: "settings.rewriteAddress",
    label: "DNS 重写地址",
    control: "text",
    placeholder: "可选 DNS 地址",
    showWhen: protocolWhen(["dns"]),
  },
  {
    key: "settings.rewritePort",
    label: "DNS 重写端口",
    control: "number",
    defaultValue: 53,
    placeholder: "0–65535",
    showWhen: protocolWhen(["dns"]),
  },
  {
    key: "settings.rules",
    label: "DNS 规则",
    control: "code",
    placeholder: '[{"action":"direct","qType":"A","domain":["example.com"],"rCode":0}]',
    showWhen: protocolWhen(["dns"]),
    description: "action：direct/drop/return/hijack；qType、domain、rCode 为可选匹配/响应字段。",
    rows: 7,
  },
  {
    key: "settings.inboundTag",
    label: "Loopback 入站 Tag",
    control: "text",
    placeholder: "inbound-01",
    showWhen: protocolWhen(["loopback"]),
    description: "Loopback 把流量重新注入指定入站。",
  },
  {
    key: "settings.sniffing.enabled",
    label: "Loopback Sniffing",
    control: "switch",
    defaultValue: false,
    showWhen: protocolWhen(["loopback"]),
  },
  {
    key: "settings.sniffing.destOverride",
    label: "Loopback 目标协议",
    control: "multiselect",
    options: sniffingDestOptions,
    showWhen: allWhen(protocolWhen(["loopback"]), when("settings.sniffing.enabled", true)),
  },
  {
    key: "settings.sniffing.metadataOnly",
    label: "Loopback 仅元数据",
    control: "switch",
    defaultValue: false,
    showWhen: allWhen(protocolWhen(["loopback"]), when("settings.sniffing.enabled", true)),
  },
  {
    key: "settings.sniffing.routeOnly",
    label: "Loopback 仅路由",
    control: "switch",
    defaultValue: false,
    showWhen: allWhen(protocolWhen(["loopback"]), when("settings.sniffing.enabled", true)),
  },
  {
    key: "settings.sniffing.ipsExcluded",
    label: "Loopback 排除 IP",
    control: "tags",
    placeholder: "IP/CIDR/geoip:private",
    showWhen: allWhen(protocolWhen(["loopback"]), when("settings.sniffing.enabled", true)),
  },
  {
    key: "settings.sniffing.domainsExcluded",
    label: "Loopback 排除域名",
    control: "tags",
    placeholder: "domain:example.com",
    showWhen: allWhen(protocolWhen(["loopback"]), when("settings.sniffing.enabled", true)),
  },
  {
    key: "settings.version",
    label: "Hysteria 版本",
    control: "select",
    options: [option("2", "2")],
    defaultValue: "2",
    showWhen: protocolWhen(["hysteria"]),
    description: "Hysteria outbound 目前固定使用版本 2。",
  },
]

const streamFields: CatalogField[] = [
  {
    key: "streamSettings.network",
    label: "传输网络",
    control: "select",
    options: [...networkOptions, option("hysteria", "Hysteria / QUIC")],
    defaultValue: "tcp",
    showWhen: showStream,
    description: "非 Hysteria 协议可选 TCP、mKCP、WebSocket、gRPC、HTTPUpgrade、XHTTP；Hysteria 固定 hysteria。",
  },
  {
    key: "streamSettings.tcpSettings.header.type",
    label: "TCP 伪装头",
    control: "select",
    options: [option("none", "无"), option("http", "HTTP")],
    defaultValue: "none",
    showWhen: allWhen(showNonHysteriaStream, networkWhen(["tcp"])),
    description: "TCP Raw 的 header type；HTTP 模式才显示 request/response 子字段。",
  },
  {
    key: "streamSettings.tcpSettings.header.request.version",
    label: "HTTP 请求版本",
    control: "text",
    defaultValue: "1.1",
    placeholder: "1.1",
    showWhen: allWhen(showNonHysteriaStream, networkWhen(["tcp"]), when("streamSettings.tcpSettings.header.type", "http")),
  },
  {
    key: "streamSettings.tcpSettings.header.request.method",
    label: "HTTP 请求方法",
    control: "text",
    defaultValue: "GET",
    placeholder: "GET",
    showWhen: allWhen(showNonHysteriaStream, networkWhen(["tcp"]), when("streamSettings.tcpSettings.header.type", "http")),
  },
  {
    key: "streamSettings.tcpSettings.header.request.path",
    label: "HTTP 请求路径",
    control: "text",
    defaultValue: "/",
    placeholder: "/, /index",
    showWhen: allWhen(showNonHysteriaStream, networkWhen(["tcp"]), when("streamSettings.tcpSettings.header.type", "http")),
  },
  {
    key: "streamSettings.tcpSettings.header.request.headers",
    label: "HTTP 请求 Headers",
    control: "code",
    placeholder: '{"Host":["example.com"]}',
    showWhen: allWhen(showNonHysteriaStream, networkWhen(["tcp"]), when("streamSettings.tcpSettings.header.type", "http")),
    rows: 4,
  },
  {
    key: "streamSettings.tcpSettings.header.response.version",
    label: "HTTP 响应版本",
    control: "text",
    defaultValue: "1.1",
    placeholder: "1.1",
    showWhen: allWhen(showNonHysteriaStream, networkWhen(["tcp"]), when("streamSettings.tcpSettings.header.type", "http")),
  },
  {
    key: "streamSettings.tcpSettings.header.response.status",
    label: "HTTP 响应状态",
    control: "text",
    defaultValue: "200",
    placeholder: "200",
    showWhen: allWhen(showNonHysteriaStream, networkWhen(["tcp"]), when("streamSettings.tcpSettings.header.type", "http")),
  },
  {
    key: "streamSettings.tcpSettings.header.response.reason",
    label: "HTTP 响应原因",
    control: "text",
    defaultValue: "OK",
    placeholder: "OK",
    showWhen: allWhen(showNonHysteriaStream, networkWhen(["tcp"]), when("streamSettings.tcpSettings.header.type", "http")),
  },
  {
    key: "streamSettings.tcpSettings.header.response.headers",
    label: "HTTP 响应 Headers",
    control: "code",
    placeholder: '{"Content-Type":["text/plain"]}',
    showWhen: allWhen(showNonHysteriaStream, networkWhen(["tcp"]), when("streamSettings.tcpSettings.header.type", "http")),
    rows: 4,
  },
  {
    key: "streamSettings.kcpSettings.mtu",
    label: "mKCP MTU",
    control: "number",
    defaultValue: 1350,
    placeholder: "576–1460",
    showWhen: allWhen(showNonHysteriaStream, networkWhen(["kcp"])),
  },
  {
    key: "streamSettings.kcpSettings.tti",
    label: "mKCP TTI",
    control: "number",
    defaultValue: 20,
    placeholder: "10–100 ms",
    showWhen: allWhen(showNonHysteriaStream, networkWhen(["kcp"])),
  },
  {
    key: "streamSettings.kcpSettings.uplinkCapacity",
    label: "mKCP 上行容量",
    control: "number",
    defaultValue: 5,
    placeholder: "Mbps",
    showWhen: allWhen(showNonHysteriaStream, networkWhen(["kcp"])),
  },
  {
    key: "streamSettings.kcpSettings.downlinkCapacity",
    label: "mKCP 下行容量",
    control: "number",
    defaultValue: 20,
    placeholder: "Mbps",
    showWhen: allWhen(showNonHysteriaStream, networkWhen(["kcp"])),
  },
  {
    key: "streamSettings.kcpSettings.cwndMultiplier",
    label: "mKCP CWND 倍率",
    control: "number",
    defaultValue: 1,
    placeholder: "至少 1",
    showWhen: allWhen(showNonHysteriaStream, networkWhen(["kcp"])),
  },
  {
    key: "streamSettings.kcpSettings.maxSendingWindow",
    label: "mKCP 最大发送窗口",
    control: "number",
    defaultValue: 2097152,
    placeholder: "字节",
    showWhen: allWhen(showNonHysteriaStream, networkWhen(["kcp"])),
  },
  {
    key: "streamSettings.wsSettings.host",
    label: "WebSocket Host",
    control: "text",
    placeholder: "可选 Host",
    showWhen: allWhen(showNonHysteriaStream, networkWhen(["ws"])),
  },
  {
    key: "streamSettings.wsSettings.path",
    label: "WebSocket Path",
    control: "text",
    defaultValue: "/",
    placeholder: "/gateway",
    showWhen: allWhen(showNonHysteriaStream, networkWhen(["ws"])),
  },
  {
    key: "streamSettings.wsSettings.heartbeatPeriod",
    label: "WebSocket 心跳周期",
    control: "number",
    defaultValue: 0,
    placeholder: "秒；0 关闭",
    showWhen: allWhen(showNonHysteriaStream, networkWhen(["ws"])),
  },
  {
    key: "streamSettings.wsSettings.headers",
    label: "WebSocket Headers",
    control: "code",
    placeholder: '{"X-Forwarded-Proto":"https"}',
    showWhen: allWhen(showNonHysteriaStream, networkWhen(["ws"])),
    rows: 4,
  },
  {
    key: "streamSettings.grpcSettings.serviceName",
    label: "gRPC Service Name",
    control: "text",
    placeholder: "可选服务名",
    showWhen: allWhen(showNonHysteriaStream, networkWhen(["grpc"])),
  },
  {
    key: "streamSettings.grpcSettings.authority",
    label: "gRPC Authority",
    control: "text",
    placeholder: "可选 authority",
    showWhen: allWhen(showNonHysteriaStream, networkWhen(["grpc"])),
  },
  {
    key: "streamSettings.grpcSettings.multiMode",
    label: "gRPC Multi Mode",
    control: "switch",
    defaultValue: false,
    showWhen: allWhen(showNonHysteriaStream, networkWhen(["grpc"])),
  },
  {
    key: "streamSettings.httpupgradeSettings.host",
    label: "HTTPUpgrade Host",
    control: "text",
    placeholder: "可选 Host",
    showWhen: allWhen(showNonHysteriaStream, networkWhen(["httpupgrade"])),
  },
  {
    key: "streamSettings.httpupgradeSettings.path",
    label: "HTTPUpgrade Path",
    control: "text",
    defaultValue: "/",
    placeholder: "/gateway",
    showWhen: allWhen(showNonHysteriaStream, networkWhen(["httpupgrade"])),
  },
  {
    key: "streamSettings.httpupgradeSettings.headers",
    label: "HTTPUpgrade Headers",
    control: "code",
    placeholder: '{"X-Forwarded-Proto":"https"}',
    showWhen: allWhen(showNonHysteriaStream, networkWhen(["httpupgrade"])),
    rows: 4,
  },
  {
    key: "streamSettings.xhttpSettings.host",
    label: "XHTTP Host",
    control: "text",
    placeholder: "可选 Host",
    showWhen: showXhttp,
  },
  {
    key: "streamSettings.xhttpSettings.path",
    label: "XHTTP Path",
    control: "text",
    defaultValue: "/",
    placeholder: "/gateway",
    showWhen: showXhttp,
  },
  {
    key: "streamSettings.xhttpSettings.mode",
    label: "XHTTP 模式",
    control: "select",
    options: xhttpModeOptions,
    defaultValue: "auto",
    showWhen: showXhttp,
  },
  {
    key: "streamSettings.xhttpSettings.xPaddingBytes",
    label: "XHTTP Padding Bytes",
    control: "text",
    defaultValue: "100-1000",
    placeholder: "100-1000",
    showWhen: showXhttp,
  },
  {
    key: "streamSettings.xhttpSettings.headers",
    label: "XHTTP Headers",
    control: "code",
    placeholder: '{"X-Forwarded-Proto":"https"}',
    showWhen: showXhttp,
    rows: 4,
  },
  {
    key: "streamSettings.xhttpSettings.xPaddingObfsMode",
    label: "XHTTP Padding Obfs",
    control: "switch",
    defaultValue: false,
    showWhen: showXhttp,
    description: "打开后才显示 key、header、placement、method 四个 Padding 注入字段。",
  },
  {
    key: "streamSettings.xhttpSettings.xPaddingKey",
    label: "Padding Key",
    control: "text",
    placeholder: "x_padding",
    showWhen: allWhen(showXhttp, when("streamSettings.xhttpSettings.xPaddingObfsMode", true)),
  },
  {
    key: "streamSettings.xhttpSettings.xPaddingHeader",
    label: "Padding Header",
    control: "text",
    placeholder: "X-Padding",
    showWhen: allWhen(showXhttp, when("streamSettings.xhttpSettings.xPaddingObfsMode", true)),
  },
  {
    key: "streamSettings.xhttpSettings.xPaddingPlacement",
    label: "Padding Placement",
    control: "select",
    options: xhttpPaddingPlacementOptions,
    showWhen: allWhen(showXhttp, when("streamSettings.xhttpSettings.xPaddingObfsMode", true)),
  },
  {
    key: "streamSettings.xhttpSettings.xPaddingMethod",
    label: "Padding Method",
    control: "select",
    options: xhttpPaddingMethodOptions,
    showWhen: allWhen(showXhttp, when("streamSettings.xhttpSettings.xPaddingObfsMode", true)),
  },
  {
    key: "streamSettings.xhttpSettings.uplinkHTTPMethod",
    label: "XHTTP 上行方法",
    control: "select",
    options: xhttpUplinkMethodOptions,
    placeholder: "默认 POST",
    showWhen: showXhttp,
    description: "GET 仅在 mode=packet-up 时允许；POST/PUT 可由运行时校验。",
  },
  {
    key: "streamSettings.xhttpSettings.sessionIDPlacement",
    label: "Session ID 位置",
    control: "select",
    options: xhttpPlacementOptions,
    placeholder: "默认 path",
    showWhen: showXhttp,
  },
  {
    key: "streamSettings.xhttpSettings.sessionIDKey",
    label: "Session ID Key",
    control: "text",
    placeholder: "x_session",
    showWhen: allWhen(showXhttp, whenNot("streamSettings.xhttpSettings.sessionIDPlacement", ["", "path"])),
  },
  {
    key: "streamSettings.xhttpSettings.sessionIDTable",
    label: "Session ID 字符表",
    control: "text",
    placeholder: "Base62 或 ASCII 字符表",
    showWhen: showXhttp,
    description: "可使用 ALPHABET、Base62、HEX 等预定义表，也可填写 ASCII 字符表。",
  },
  {
    key: "streamSettings.xhttpSettings.sessionIDLength",
    label: "Session ID 长度",
    control: "text",
    placeholder: "8-16",
    showWhen: allWhen(showXhttp, whenNot("streamSettings.xhttpSettings.sessionIDTable", "")),
  },
  {
    key: "streamSettings.xhttpSettings.seqPlacement",
    label: "Sequence 位置",
    control: "select",
    options: xhttpPlacementOptions,
    placeholder: "默认 path",
    showWhen: showXhttp,
  },
  {
    key: "streamSettings.xhttpSettings.seqKey",
    label: "Sequence Key",
    control: "text",
    placeholder: "x_seq",
    showWhen: allWhen(showXhttp, whenNot("streamSettings.xhttpSettings.seqPlacement", ["", "path"])),
  },
  {
    key: "streamSettings.xhttpSettings.scMinPostsIntervalMs",
    label: "最小上传间隔",
    control: "text",
    placeholder: "例如 50-150",
    showWhen: allWhen(showXhttp, when("streamSettings.xhttpSettings.mode", ["packet-up", "auto"])),
  },
  {
    key: "streamSettings.xhttpSettings.scMaxEachPostBytes",
    label: "单次上传最大字节",
    control: "text",
    placeholder: "1000000",
    showWhen: allWhen(showXhttp, when("streamSettings.xhttpSettings.mode", ["packet-up", "auto"])),
  },
  {
    key: "streamSettings.xhttpSettings.uplinkDataPlacement",
    label: "上行数据位置",
    control: "select",
    options: xhttpUplinkDataPlacementOptions,
    placeholder: "默认 auto",
    showWhen: allWhen(showXhttp, when("streamSettings.xhttpSettings.mode", ["packet-up", "auto"])),
  },
  {
    key: "streamSettings.xhttpSettings.uplinkDataKey",
    label: "上行数据 Key",
    control: "text",
    placeholder: "x_data",
    showWhen: allWhen(
      showXhttp,
      when("streamSettings.xhttpSettings.mode", ["packet-up", "auto"]),
      whenNot("streamSettings.xhttpSettings.uplinkDataPlacement", ["", "body"]),
    ),
  },
  {
    key: "streamSettings.xhttpSettings.uplinkChunkSize",
    label: "上行 Chunk 大小",
    control: "number",
    defaultValue: 0,
    placeholder: "0 不限制",
    showWhen: allWhen(
      showXhttp,
      when("streamSettings.xhttpSettings.mode", ["packet-up", "auto"]),
      whenNot("streamSettings.xhttpSettings.uplinkDataPlacement", ["", "body"]),
    ),
  },
  {
    key: "streamSettings.xhttpSettings.noGRPCHeader",
    label: "省略 gRPC Header",
    control: "switch",
    defaultValue: false,
    showWhen: allWhen(showXhttp, when("streamSettings.xhttpSettings.mode", ["stream-up", "stream-one"])),
  },
  {
    key: "streamSettings.xhttpSettings.enableXmux",
    label: "启用 XHTTP XMUX",
    control: "switch",
    defaultValue: false,
    showWhen: showXhttp,
    description: "这是 XHTTP 的连接池复用，不等同于顶层 Mux；打开后 maxConcurrency 与 maxConnections 二选一。",
  },
  {
    key: "streamSettings.xhttpSettings.xmux.maxConcurrency",
    label: "XMUX 最大并发",
    control: "text",
    defaultValue: "16-32",
    placeholder: "16-32",
    showWhen: allWhen(showXhttp, when("streamSettings.xhttpSettings.enableXmux", true)),
  },
  {
    key: "streamSettings.xhttpSettings.xmux.maxConnections",
    label: "XMUX 最大连接",
    control: "text",
    defaultValue: 3,
    placeholder: "0 或正整数/range",
    showWhen: allWhen(showXhttp, when("streamSettings.xhttpSettings.enableXmux", true)),
    description: "与 maxConcurrency 互斥；设置正数时运行时应清除 maxConcurrency。",
  },
  {
    key: "streamSettings.xhttpSettings.xmux.cMaxReuseTimes",
    label: "XMUX 最大复用次数",
    control: "text",
    placeholder: "可选范围",
    showWhen: allWhen(showXhttp, when("streamSettings.xhttpSettings.enableXmux", true)),
  },
  {
    key: "streamSettings.xhttpSettings.xmux.hMaxRequestTimes",
    label: "XMUX 最大请求次数",
    control: "text",
    defaultValue: "600-900",
    placeholder: "600-900",
    showWhen: allWhen(showXhttp, when("streamSettings.xhttpSettings.enableXmux", true)),
  },
  {
    key: "streamSettings.xhttpSettings.xmux.hMaxReusableSecs",
    label: "XMUX 最大复用秒数",
    control: "text",
    defaultValue: "1800-3000",
    placeholder: "1800-3000",
    showWhen: allWhen(showXhttp, when("streamSettings.xhttpSettings.enableXmux", true)),
  },
  {
    key: "streamSettings.xhttpSettings.xmux.hKeepAlivePeriod",
    label: "XMUX Keepalive 周期",
    control: "number",
    defaultValue: 0,
    placeholder: "秒；0 关闭",
    showWhen: allWhen(showXhttp, when("streamSettings.xhttpSettings.enableXmux", true)),
  },
  {
    key: "streamSettings.hysteriaSettings.version",
    label: "Hysteria 传输版本",
    control: "select",
    options: [option("2", "2")],
    defaultValue: "2",
    showWhen: allWhen(protocolWhen(["hysteria"]), networkWhen(["hysteria"])),
  },
  {
    key: "streamSettings.hysteriaSettings.auth",
    label: "Hysteria Auth",
    control: "password",
    placeholder: "可选认证密码",
    sensitive: true,
    showWhen: allWhen(protocolWhen(["hysteria"]), networkWhen(["hysteria"])),
  },
  {
    key: "streamSettings.hysteriaSettings.udpIdleTimeout",
    label: "Hysteria UDP 空闲超时",
    control: "number",
    defaultValue: 60,
    placeholder: "2–600 秒",
    showWhen: allWhen(protocolWhen(["hysteria"]), networkWhen(["hysteria"])),
  },
  {
    key: "streamSettings.hysteriaSettings.masquerade",
    label: "Hysteria Masquerade",
    control: "code",
    placeholder: '{"type":"proxy","url":"https://example.com"}',
    showWhen: allWhen(protocolWhen(["hysteria"]), networkWhen(["hysteria"])),
    description: "可选伪装对象；type 可为空、proxy、file、string，具体字段按 type 显示。",
    rows: 7,
  },
]

const securityFields: CatalogField[] = [
  {
    key: "streamSettings.security",
    label: "传输安全",
    control: "select",
    options: securityOptions,
    defaultValue: "none",
    showWhen: showStream,
    description: "Hysteria 传输固定 TLS；Reality 仅 VLESS/Trojan 且受网络能力限制。",
  },
  {
    key: "streamSettings.tlsSettings.serverName",
    label: "TLS SNI",
    control: "text",
    placeholder: "example.com",
    showWhen: showTls,
  },
  {
    key: "streamSettings.tlsSettings.fingerprint",
    label: "TLS uTLS 指纹",
    control: "select",
    options: utlsOptions,
    placeholder: "默认",
    showWhen: showTls,
  },
  {
    key: "streamSettings.tlsSettings.alpn",
    label: "TLS ALPN",
    control: "multiselect",
    options: alpnOptions,
    placeholder: "选择 ALPN",
    showWhen: showTls,
  },
  {
    key: "streamSettings.tlsSettings.echConfigList",
    label: "TLS ECH",
    control: "textarea",
    placeholder: "可选 ECH config list",
    showWhen: showTls,
    rows: 3,
  },
  {
    key: "streamSettings.tlsSettings.verifyPeerCertByName",
    label: "TLS 证书名称校验",
    control: "text",
    placeholder: "cloudflare-dns.com",
    showWhen: showTls,
    description: "对应 outbound 表单的 verifyPeerCertByName；不要与 allowInsecure 混用。",
  },
  {
    key: "streamSettings.tlsSettings.pinnedPeerCertSha256",
    label: "TLS 证书 Pin",
    control: "text",
    placeholder: "base64 SHA-256",
    showWhen: showTls,
  },
  {
    key: "streamSettings.realitySettings.serverName",
    label: "Reality SNI",
    control: "text",
    placeholder: "example.com",
    showWhen: showReality,
  },
  {
    key: "streamSettings.realitySettings.fingerprint",
    label: "Reality uTLS 指纹",
    control: "select",
    options: options([
      "chrome",
      "firefox",
      "safari",
      "ios",
      "android",
      "edge",
      "360",
      "qq",
      "random",
      "randomized",
      "randomizednoalpn",
      "unsafe",
    ]),
    defaultValue: "chrome",
    showWhen: showReality,
  },
  {
    key: "streamSettings.realitySettings.shortId",
    label: "Reality Short ID",
    control: "text",
    placeholder: "短 ID",
    showWhen: showReality,
  },
  {
    key: "streamSettings.realitySettings.spiderX",
    label: "Reality SpiderX",
    control: "text",
    placeholder: "/",
    showWhen: showReality,
  },
  {
    key: "streamSettings.realitySettings.publicKey",
    label: "Reality Public Key",
    control: "textarea",
    placeholder: "base64 public key",
    showWhen: showReality,
    rows: 2,
  },
  {
    key: "streamSettings.realitySettings.mldsa65Verify",
    label: "Reality ML-DSA Verify",
    control: "textarea",
    placeholder: "可选验证值",
    showWhen: showReality,
    rows: 2,
  },
]

const outboundSockoptFields: CatalogField[] = [
  {
    key: "streamSettings.sockopt.enabled",
    label: "启用 Sockopt",
    control: "switch",
    defaultValue: false,
    description: "Sockopt 可附着于可传输出站、transportless 出站及 WireGuard；关闭时不写 streamSettings.sockopt。",
  },
  {
    key: "streamSettings.sockopt.dialerProxy",
    label: "链式代理出站 Tag",
    control: "select",
    placeholder: "选择上游出站 Tag",
    showWhen: when("streamSettings.sockopt.enabled", true),
    description: "通过 dialerProxy 链到单个出站；HostSockoptForm 会排除 balancer/blackhole，目录实现也应沿用该限制。",
  },
  {
    key: "streamSettings.sockopt.domainStrategy",
    label: "Sockopt 解析策略",
    control: "select",
    options: sockoptDomainStrategyOptions,
    defaultValue: "AsIs",
    showWhen: when("streamSettings.sockopt.enabled", true),
  },
  {
    key: "streamSettings.sockopt.addressPortStrategy",
    label: "地址/端口策略",
    control: "select",
    options: addressPortStrategyOptions,
    defaultValue: "none",
    showWhen: when("streamSettings.sockopt.enabled", true),
  },
  {
    key: "streamSettings.sockopt.tcpKeepAliveInterval",
    label: "TCP Keepalive 间隔",
    control: "number",
    defaultValue: 0,
    placeholder: "秒；0 使用系统默认",
    showWhen: when("streamSettings.sockopt.enabled", true),
  },
  {
    key: "streamSettings.sockopt.tcpFastOpen",
    label: "TCP Fast Open",
    control: "switch",
    defaultValue: false,
    showWhen: when("streamSettings.sockopt.enabled", true),
  },
  {
    key: "streamSettings.sockopt.tcpMptcp",
    label: "Multipath TCP",
    control: "switch",
    defaultValue: false,
    showWhen: when("streamSettings.sockopt.enabled", true),
  },
  {
    key: "streamSettings.sockopt.penetrate",
    label: "穿透模式",
    control: "switch",
    defaultValue: false,
    showWhen: when("streamSettings.sockopt.enabled", true),
  },
  {
    key: "streamSettings.sockopt.mark",
    label: "Fwmark",
    control: "number",
    defaultValue: 0,
    placeholder: "0 表示不设置",
    showWhen: when("streamSettings.sockopt.enabled", true),
  },
  {
    key: "streamSettings.sockopt.interface",
    label: "网络接口",
    control: "text",
    placeholder: "例如：eth0",
    showWhen: when("streamSettings.sockopt.enabled", true),
  },
  {
    key: "streamSettings.sockopt.tproxy",
    label: "TProxy",
    control: "select",
    options: options(["off", "redirect", "tproxy"]),
    defaultValue: "off",
    showWhen: when("streamSettings.sockopt.enabled", true),
  },
  {
    key: "streamSettings.sockopt.tcpcongestion",
    label: "TCP 拥塞控制",
    control: "select",
    options: options(["bbr", "cubic", "reno"]),
    defaultValue: "bbr",
    showWhen: when("streamSettings.sockopt.enabled", true),
  },
  {
    key: "streamSettings.sockopt.tcpUserTimeout",
    label: "TCP 用户超时",
    control: "number",
    defaultValue: 0,
    placeholder: "毫秒；0 使用系统默认",
    showWhen: when("streamSettings.sockopt.enabled", true),
  },
  {
    key: "streamSettings.sockopt.tcpKeepAliveIdle",
    label: "TCP Keepalive 空闲",
    control: "number",
    defaultValue: 0,
    placeholder: "秒；0 使用系统默认",
    showWhen: when("streamSettings.sockopt.enabled", true),
  },
  {
    key: "streamSettings.sockopt.tcpMaxSeg",
    label: "TCP 最大分段",
    control: "number",
    defaultValue: 0,
    placeholder: "0 使用系统默认",
    showWhen: when("streamSettings.sockopt.enabled", true),
  },
  {
    key: "streamSettings.sockopt.tcpWindowClamp",
    label: "TCP Window Clamp",
    control: "number",
    defaultValue: 0,
    placeholder: "0 使用系统默认",
    showWhen: when("streamSettings.sockopt.enabled", true),
  },
  {
    key: "streamSettings.sockopt.happyEyeballs.enabled",
    label: "Happy Eyeballs",
    control: "switch",
    defaultValue: false,
    showWhen: when("streamSettings.sockopt.enabled", true),
  },
  {
    key: "streamSettings.sockopt.happyEyeballs.tryDelayMs",
    label: "Happy Eyeballs 尝试延迟",
    control: "number",
    defaultValue: 250,
    placeholder: "毫秒；250 常用",
    showWhen: allWhen(when("streamSettings.sockopt.enabled", true), when("streamSettings.sockopt.happyEyeballs.enabled", true)),
  },
  {
    key: "streamSettings.sockopt.happyEyeballs.prioritizeIPv6",
    label: "优先 IPv6",
    control: "switch",
    defaultValue: false,
    showWhen: allWhen(when("streamSettings.sockopt.enabled", true), when("streamSettings.sockopt.happyEyeballs.enabled", true)),
  },
  {
    key: "streamSettings.sockopt.happyEyeballs.interleave",
    label: "地址交错数",
    control: "number",
    defaultValue: 1,
    placeholder: "至少 1",
    showWhen: allWhen(when("streamSettings.sockopt.enabled", true), when("streamSettings.sockopt.happyEyeballs.enabled", true)),
  },
  {
    key: "streamSettings.sockopt.happyEyeballs.maxConcurrentTry",
    label: "最大并发尝试",
    control: "number",
    defaultValue: 4,
    placeholder: "0 表示不限制",
    showWhen: allWhen(when("streamSettings.sockopt.enabled", true), when("streamSettings.sockopt.happyEyeballs.enabled", true)),
  },
  {
    key: "streamSettings.sockopt.customSockopt",
    label: "自定义 Socket 选项",
    control: "code",
    placeholder: '[{"system":"linux","type":"int","level":"6","opt":"1","value":1}]',
    showWhen: when("streamSettings.sockopt.enabled", true),
    description: "JSON 数组；system 可为 linux/windows/darwin，type 可为 int/str。",
    rows: 5,
  },
]

const outboundMuxFields: CatalogField[] = [
  {
    key: "mux.enabled",
    label: "顶层 Mux",
    control: "switch",
    defaultValue: false,
    showWhen: showMuxProtocol,
    description: "3X-UI 只对 vmess/vless/trojan/shadowsocks/http/socks 显示；VLESS 有 flow 或 XHTTP 时需隐藏。",
  },
  {
    key: "mux.concurrency",
    label: "Mux 并发数",
    control: "number",
    defaultValue: 8,
    placeholder: "-1 至 1024",
    showWhen: allWhen(showMuxProtocol, when("mux.enabled", true)),
  },
  {
    key: "mux.xudpConcurrency",
    label: "XUDP 并发数",
    control: "number",
    defaultValue: 16,
    placeholder: "-1 至 1024",
    showWhen: allWhen(showMuxProtocol, when("mux.enabled", true)),
  },
  {
    key: "mux.xudpProxyUDP443",
    label: "XUDP UDP/443",
    control: "select",
    options: options(["reject", "allow", "skip"]),
    defaultValue: "reject",
    showWhen: allWhen(showMuxProtocol, when("mux.enabled", true)),
  },
]

const outboundFinalMaskFields: CatalogField[] = [
  {
    key: "streamSettings.finalmask.tcp",
    label: "TCP Final Mask",
    control: "code",
    placeholder: '{"tcp":[{"type":"fragment","settings":{}}]}',
    options: finalMaskTcpTypeOptions,
    showWhen: networkWhen(["tcp", "httpupgrade", "ws", "grpc", "xhttp"]),
    description: "TCP mask 类型：fragment、header-custom、sudoku、xmc；每个 settings 按类型变化。",
    rows: 7,
  },
  {
    key: "streamSettings.finalmask.udp",
    label: "UDP Final Mask",
    control: "code",
    placeholder: '{"udp":[{"type":"salamander","settings":{}}]}',
    options: finalMaskUdpTypeOptions,
    showWhen: protocolWhen(["vmess", "vless", "trojan", "shadowsocks", "hysteria", "wireguard"]),
    description: "UDP mask 类型由协议/传输共同决定；WireGuard 也支持该数组但没有 network 字段。",
    rows: 7,
  },
  {
    key: "streamSettings.finalmask.quicParams",
    label: "QUIC 参数",
    control: "code",
    placeholder: '{"congestion":"bbr","udpHop":{"ports":"20000-50000","interval":"5-10"}}',
    showWhen: networkWhen(["xhttp", "hysteria"]),
    description: "xHTTP/Hysteria 可见；包括 congestion、BBR profile、窗口、timeout、UDP hop。",
    rows: 8,
  },
]

export const outboundCatalog: CatalogTab[] = [
  {
    id: "outbound-identity",
    title: "出站身份",
    description: "协议、Tag、源地址与目标解析策略。",
    sections: [{ id: "outbound-identity", title: "基础", fields: outboundIdentityFields }],
  },
  {
    id: "outbound-protocol",
    title: "协议参数",
    description: "按 3X-UI 的 outbound settings 分支展示连接目标和协议专属字段。",
    sections: [{ id: "outbound-settings", title: "协议设置", fields: outboundServerFields }],
  },
  {
    id: "outbound-stream",
    title: "传输",
    description: "网络类型及 TCP、mKCP、WebSocket、gRPC、HTTPUpgrade、XHTTP、Hysteria 的依赖字段。",
    sections: [{ id: "outbound-stream", title: "Stream Settings", fields: streamFields }],
  },
  {
    id: "outbound-security",
    title: "安全",
    description: "TLS/Reality 的能力约束与客户端握手参数。",
    sections: [{ id: "outbound-security", title: "Security Settings", fields: securityFields }],
  },
  {
    id: "outbound-runtime",
    title: "运行参数",
    description: "Sockopt、链式代理、顶层 Mux 与 Final Mask。",
    sections: [
      { id: "outbound-sockopt", title: "Sockopt 与链式代理", fields: outboundSockoptFields },
      { id: "outbound-mux", title: "Mux", fields: outboundMuxFields },
      { id: "outbound-final-mask", title: "Final Mask", fields: outboundFinalMaskFields },
    ],
  },
]

/** Combined view for consumers that want one field source for both editors. */
export const outboundHostCatalog: CatalogTab[] = [...managedHostCatalog, ...outboundCatalog]

/** Short alias for callers that refer to the Managed Host editor as `host`. */
export const hostCatalog: CatalogTab[] = managedHostCatalog
